USE ai_quality_control;

-- ============================================================
-- Inspect sample 020: L360M_customer_HXPIPE
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/CUST-HXPIPE-SIM-2026-L360M_customer_agreement.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_20', 'PRODUCT_VARIETY', '管线钢热轧卷', '管线钢热轧卷', '', 401, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_20', 'PRODUCT_GRADE', 'L360M-QA0623', 'L360M-QA0623', '', 402, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW()),
('td_cust_20', 'QC_CUSTOMER', 'TD-CUST-HXPIPE', '华信管业', '', 403, 1, 0, '测试包：客户协议检验记录样例', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_ceq', '碳当量', 'TD_CEQ', 'COMPOSITION', '%', '熔炼分析', '焊接性控制指标', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_20_l360m_customer_hxpipe', 'CUSTOMER', 'AGREEMENT HXPIPE-SIM-2026-005-QA0623', '华信管业L360M管线钢热轧卷供货质量协议（QA0623隔离模拟客户协议）', '管线钢热轧卷', 'L360M-QA0623', '厚度5.00mm-18.00mm，宽度1000mm-1800mm', '协议V1.0-QA0623', '2026-03-01', '2026-12-31', 'PUBLISHED', 'TD-CUST-HXPIPE', '来源PDF：CUST-HXPIPE-SIM-2026-L360M_customer_agreement.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_20_1', 'td_std_20_l360m_customer_hxpipe', 'ind003', 510, 360, 1, 520, 350, NOW(), NOW()),
('td_si_20_2', 'td_std_20_l360m_customer_hxpipe', 'ind001', 650, 460, 1, NULL, NULL, NOW(), NOW()),
('td_si_20_3', 'td_std_20_l360m_customer_hxpipe', 'ind002', NULL, 20, 1, NULL, 19, NOW(), NOW()),
('td_si_20_4', 'td_std_20_l360m_customer_hxpipe', 'td_ind_ceq', 0.42, NULL, 1, 0.44, NULL, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_20_1', 'HT-TD-20-QUAL-001', 'COIL-TD-20-QUAL-001', 'HT-TD-20-QUAL-001', 'MIDDLE', '2026-06-27 09:00:00', '021001', 'TD-CUST-HXPIPE', '管线钢热轧卷', 'L360M-QA0623', '厚度10.00mm，宽度1500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_20_2', 'HT-TD-20-EDGE-001', 'COIL-TD-20-EDGE-001', 'HT-TD-20-EDGE-001', 'HEAD', '2026-06-27 10:00:00', '021001', 'TD-CUST-HXPIPE', '管线钢热轧卷', 'L360M-QA0623', '厚度10.00mm，宽度1500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_20_3', 'HT-TD-20-CONC-001', 'COIL-TD-20-CONC-001', 'HT-TD-20-CONC-001', 'TAIL', '2026-06-27 11:00:00', '021001', 'TD-CUST-HXPIPE', '管线钢热轧卷', 'L360M-QA0623', '厚度10.00mm，宽度1500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_20_4', 'HT-TD-20-REINS-001', 'COIL-TD-20-REINS-001', 'HT-TD-20-REINS-001', 'MIDDLE', '2026-06-27 12:00:00', '021001', 'TD-CUST-HXPIPE', '管线钢热轧卷', 'L360M-QA0623', '厚度10.00mm，宽度1500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_20_5', 'HT-TD-20-UNQ-001', 'COIL-TD-20-UNQ-001', 'HT-TD-20-UNQ-001', 'HEAD', '2026-06-27 13:00:00', '021001', 'TD-CUST-HXPIPE', '管线钢热轧卷', 'L360M-QA0623', '厚度10.00mm，宽度1500mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_20_1_1', 'td_ins_20_1', 'ind003', 435, NULL, 'system', NOW(), NOW()),
('td_iv_20_1_2', 'td_ins_20_1', 'ind001', 555, NULL, 'system', NOW(), NOW()),
('td_iv_20_1_3', 'td_ins_20_1', 'ind002', 22, NULL, 'system', NOW(), NOW()),
('td_iv_20_1_4', 'td_ins_20_1', 'td_ind_ceq', 0.40, NULL, 'system', NOW(), NOW()),
('td_iv_20_2_1', 'td_ins_20_2', 'ind003', 360, NULL, 'system', NOW(), NOW()),
('td_iv_20_2_2', 'td_ins_20_2', 'ind001', 460, NULL, 'system', NOW(), NOW()),
('td_iv_20_2_3', 'td_ins_20_2', 'ind002', 20, NULL, 'system', NOW(), NOW()),
('td_iv_20_2_4', 'td_ins_20_2', 'td_ind_ceq', 0.42, NULL, 'system', NOW(), NOW()),
('td_iv_20_3_1', 'td_ins_20_3', 'ind003', 355, NULL, 'system', NOW(), NOW()),
('td_iv_20_3_2', 'td_ins_20_3', 'ind001', 555, NULL, 'system', NOW(), NOW()),
('td_iv_20_3_3', 'td_ins_20_3', 'ind002', 22, NULL, 'system', NOW(), NOW()),
('td_iv_20_3_4', 'td_ins_20_3', 'td_ind_ceq', 0.40, NULL, 'system', NOW(), NOW()),
('td_iv_20_4_1', 'td_ins_20_4', 'ind003', 435, NULL, 'system', NOW(), NOW()),
('td_iv_20_4_2', 'td_ins_20_4', 'ind001', 455, NULL, 'system', NOW(), NOW()),
('td_iv_20_4_3', 'td_ins_20_4', 'ind002', 22, NULL, 'system', NOW(), NOW()),
('td_iv_20_4_4', 'td_ins_20_4', 'td_ind_ceq', 0.40, NULL, 'system', NOW(), NOW()),
('td_iv_20_5_1', 'td_ins_20_5', 'ind003', 339.99, NULL, 'system', NOW(), NOW()),
('td_iv_20_5_2', 'td_ins_20_5', 'ind001', 555, NULL, 'system', NOW(), NOW()),
('td_iv_20_5_3', 'td_ins_20_5', 'ind002', 22, NULL, 'system', NOW(), NOW()),
('td_iv_20_5_4', 'td_ins_20_5', 'td_ind_ceq', 0.40, NULL, 'system', NOW(), NOW());
