USE ai_quality_control;

-- ============================================================
-- Inspect sample 014: NM400_wear_plate
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/Q-JH-STEEL-SIM-040-2026_NM400_wear_plate_enterprise.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_14', 'PRODUCT_VARIETY', '调质耐磨钢板', '调质耐磨钢板', '', 341, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_14', 'PRODUCT_GRADE', 'NM400-QA0623', 'NM400-QA0623', '', 342, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind004', '厚度公差', 'Δt', 'DIMENSION', 'mm', '千分尺测厚', '实测厚度与名义厚度之差', 'ACTIVE', 0, NOW(), NOW()),
('ind007', '硬度', 'HV', 'PERFORMANCE', 'HV', 'GB/T 4340.1', '维氏硬度', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_14_nm400_wear_plate', 'ENTERPRISE', 'Q/JH STEEL SIM 040-2026-QA0623', 'NM400调质耐磨钢板企业标准（QA0623隔离模拟企标）', '调质耐磨钢板', 'NM400-QA0623', '厚度6.00mm-40.00mm，宽度1500mm-2500mm', 'V2026.1-QA0623', '2026-03-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：Q-JH-STEEL-SIM-040-2026_NM400_wear_plate_enterprise.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_14_1', 'td_std_14_nm400_wear_plate', 'ind007', 440, 360, 1, 450, 350, NOW(), NOW()),
('td_si_14_2', 'td_std_14_nm400_wear_plate', 'ind001', NULL, 1200, 1, NULL, NULL, NOW(), NOW()),
('td_si_14_3', 'td_std_14_nm400_wear_plate', 'ind002', NULL, 8, 1, NULL, 7, NOW(), NOW()),
('td_si_14_4', 'td_std_14_nm400_wear_plate', 'ind004', 0.3, -0.3, 1, 0.35, -0.35, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_14_1', 'HT-TD-14-QUAL-001', 'COIL-TD-14-QUAL-001', 'HT-TD-14-QUAL-001', 'MIDDLE', '2026-06-26 09:42:00', '021001', NULL, '调质耐磨钢板', 'NM400-QA0623', '厚度20.00mm，宽度2200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_14_2', 'HT-TD-14-EDGE-001', 'COIL-TD-14-EDGE-001', 'HT-TD-14-EDGE-001', 'HEAD', '2026-06-26 10:42:00', '021001', NULL, '调质耐磨钢板', 'NM400-QA0623', '厚度20.00mm，宽度2200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_14_3', 'HT-TD-14-CONC-001', 'COIL-TD-14-CONC-001', 'HT-TD-14-CONC-001', 'TAIL', '2026-06-26 11:42:00', '021001', NULL, '调质耐磨钢板', 'NM400-QA0623', '厚度20.00mm，宽度2200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_14_4', 'HT-TD-14-REINS-001', 'COIL-TD-14-REINS-001', 'HT-TD-14-REINS-001', 'MIDDLE', '2026-06-26 12:42:00', '021001', NULL, '调质耐磨钢板', 'NM400-QA0623', '厚度20.00mm，宽度2200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_14_5', 'HT-TD-14-UNQ-001', 'COIL-TD-14-UNQ-001', 'HT-TD-14-UNQ-001', 'HEAD', '2026-06-26 13:42:00', '021001', NULL, '调质耐磨钢板', 'NM400-QA0623', '厚度20.00mm，宽度2200mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_14_1_1', 'td_ins_14_1', 'ind007', 400, NULL, 'system', NOW(), NOW()),
('td_iv_14_1_2', 'td_ins_14_1', 'ind001', 1225, NULL, 'system', NOW(), NOW()),
('td_iv_14_1_3', 'td_ins_14_1', 'ind002', 8.2, NULL, 'system', NOW(), NOW()),
('td_iv_14_1_4', 'td_ins_14_1', 'ind004', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_14_2_1', 'td_ins_14_2', 'ind007', 360, NULL, 'system', NOW(), NOW()),
('td_iv_14_2_2', 'td_ins_14_2', 'ind001', 1200, NULL, 'system', NOW(), NOW()),
('td_iv_14_2_3', 'td_ins_14_2', 'ind002', 8, NULL, 'system', NOW(), NOW()),
('td_iv_14_2_4', 'td_ins_14_2', 'ind004', -0.3, NULL, 'system', NOW(), NOW()),
('td_iv_14_3_1', 'td_ins_14_3', 'ind007', 355, NULL, 'system', NOW(), NOW()),
('td_iv_14_3_2', 'td_ins_14_3', 'ind001', 1225, NULL, 'system', NOW(), NOW()),
('td_iv_14_3_3', 'td_ins_14_3', 'ind002', 8.2, NULL, 'system', NOW(), NOW()),
('td_iv_14_3_4', 'td_ins_14_3', 'ind004', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_14_4_1', 'td_ins_14_4', 'ind007', 400, NULL, 'system', NOW(), NOW()),
('td_iv_14_4_2', 'td_ins_14_4', 'ind001', 1195, NULL, 'system', NOW(), NOW()),
('td_iv_14_4_3', 'td_ins_14_4', 'ind002', 8.2, NULL, 'system', NOW(), NOW()),
('td_iv_14_4_4', 'td_ins_14_4', 'ind004', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_14_5_1', 'td_ins_14_5', 'ind007', 339.99, NULL, 'system', NOW(), NOW()),
('td_iv_14_5_2', 'td_ins_14_5', 'ind001', 1225, NULL, 'system', NOW(), NOW()),
('td_iv_14_5_3', 'td_ins_14_5', 'ind002', 8.2, NULL, 'system', NOW(), NOW()),
('td_iv_14_5_4', 'td_ins_14_5', 'ind004', 0.0, NULL, 'system', NOW(), NOW());
