USE ai_quality_control;

-- ============================================================
-- Inspect sample 004: DX51D_Z_galvanized
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/GB-T-SIM-2518-2026_DX51D-Z_galvanized_sheet_national.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_04', 'PRODUCT_VARIETY', '镀锌板', '镀锌板', '', 241, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_04', 'PRODUCT_GRADE', 'DX51D+Z-QA0623', 'DX51D+Z-QA0623', '', 242, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind004', '厚度公差', 'Δt', 'DIMENSION', 'mm', '千分尺测厚', '实测厚度与名义厚度之差', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_coat_mass', '镀层重量', 'TD_COAT', 'PERFORMANCE', 'g/m2', '三点称量法', '双面镀层重量', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_04_dx51d_z_galvanized', 'NATIONAL', 'GB/T SIM 2518-2026-QA0623', 'DX51D+Z连续热镀锌钢板及钢带质量要求（QA0623隔离模拟国标）', '镀锌板', 'DX51D+Z-QA0623', '厚度0.50mm-2.50mm，宽度800mm-1500mm', '2026版-QA0623', '2026-04-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：GB-T-SIM-2518-2026_DX51D-Z_galvanized_sheet_national.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_04_1', 'td_std_04_dx51d_z_galvanized', 'td_ind_coat_mass', 275, 80, 1, 285, 70, NOW(), NOW()),
('td_si_04_2', 'td_std_04_dx51d_z_galvanized', 'ind001', 500, 270, 1, NULL, NULL, NOW(), NOW()),
('td_si_04_3', 'td_std_04_dx51d_z_galvanized', 'ind002', NULL, 22, 1, NULL, 20, NOW(), NOW()),
('td_si_04_4', 'td_std_04_dx51d_z_galvanized', 'ind004', 0.08, -0.08, 1, 0.1, -0.1, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_04_1', 'HT-TD-04-QUAL-001', 'COIL-TD-04-QUAL-001', 'HT-TD-04-QUAL-001', 'MIDDLE', '2026-06-23 09:12:00', '021001', NULL, '镀锌板', 'DX51D+Z-QA0623', '厚度1.00mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_04_2', 'HT-TD-04-EDGE-001', 'COIL-TD-04-EDGE-001', 'HT-TD-04-EDGE-001', 'HEAD', '2026-06-23 10:12:00', '021001', NULL, '镀锌板', 'DX51D+Z-QA0623', '厚度1.00mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_04_3', 'HT-TD-04-CONC-001', 'COIL-TD-04-CONC-001', 'HT-TD-04-CONC-001', 'TAIL', '2026-06-23 11:12:00', '021001', NULL, '镀锌板', 'DX51D+Z-QA0623', '厚度1.00mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_04_4', 'HT-TD-04-REINS-001', 'COIL-TD-04-REINS-001', 'HT-TD-04-REINS-001', 'MIDDLE', '2026-06-23 12:12:00', '021001', NULL, '镀锌板', 'DX51D+Z-QA0623', '厚度1.00mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_04_5', 'HT-TD-04-UNQ-001', 'COIL-TD-04-UNQ-001', 'HT-TD-04-UNQ-001', 'HEAD', '2026-06-23 13:12:00', '021001', NULL, '镀锌板', 'DX51D+Z-QA0623', '厚度1.00mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_04_1_1', 'td_ins_04_1', 'td_ind_coat_mass', 177.5, NULL, 'system', NOW(), NOW()),
('td_iv_04_1_2', 'td_ins_04_1', 'ind001', 385, NULL, 'system', NOW(), NOW()),
('td_iv_04_1_3', 'td_ins_04_1', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_04_1_4', 'td_ins_04_1', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_04_2_1', 'td_ins_04_2', 'td_ind_coat_mass', 80, NULL, 'system', NOW(), NOW()),
('td_iv_04_2_2', 'td_ins_04_2', 'ind001', 270, NULL, 'system', NOW(), NOW()),
('td_iv_04_2_3', 'td_ins_04_2', 'ind002', 22, NULL, 'system', NOW(), NOW()),
('td_iv_04_2_4', 'td_ins_04_2', 'ind004', -0.08, NULL, 'system', NOW(), NOW()),
('td_iv_04_3_1', 'td_ins_04_3', 'td_ind_coat_mass', 75, NULL, 'system', NOW(), NOW()),
('td_iv_04_3_2', 'td_ins_04_3', 'ind001', 385, NULL, 'system', NOW(), NOW()),
('td_iv_04_3_3', 'td_ins_04_3', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_04_3_4', 'td_ins_04_3', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_04_4_1', 'td_ins_04_4', 'td_ind_coat_mass', 177.5, NULL, 'system', NOW(), NOW()),
('td_iv_04_4_2', 'td_ins_04_4', 'ind001', 265, NULL, 'system', NOW(), NOW()),
('td_iv_04_4_3', 'td_ins_04_4', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_04_4_4', 'td_ins_04_4', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_04_5_1', 'td_ins_04_5', 'td_ind_coat_mass', 59.99, NULL, 'system', NOW(), NOW()),
('td_iv_04_5_2', 'td_ins_04_5', 'ind001', 385, NULL, 'system', NOW(), NOW()),
('td_iv_04_5_3', 'td_ins_04_5', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_04_5_4', 'td_ins_04_5', 'ind004', 0.00, NULL, 'system', NOW(), NOW());
