USE ai_quality_control;

-- ============================================================
-- Inspect sample 009: 50W800_electrical
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/GB-T-SIM-2521-2026_50W800_electrical_steel_national.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_09', 'PRODUCT_VARIETY', '冷轧无取向电工钢', '冷轧无取向电工钢', '', 291, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_09', 'PRODUCT_GRADE', '50W800-QA0623', '50W800-QA0623', '', 292, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind004', '厚度公差', 'Δt', 'DIMENSION', 'mm', '千分尺测厚', '实测厚度与名义厚度之差', 'ACTIVE', 0, NOW(), NOW()),
('ind007', '硬度', 'HV', 'PERFORMANCE', 'HV', 'GB/T 4340.1', '维氏硬度', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_b50', '磁感B50', 'TD_B50', 'PERFORMANCE', 'T', '磁性能试验', '5000A/m磁感应强度', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_p15_50', '铁损P15/50', 'TD_P15_50', 'PERFORMANCE', 'W/kg', '磁性能试验', '1.5T/50Hz单位铁损', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_09_50w800_electrical', 'NATIONAL', 'GB/T SIM 2521-2026-QA0623', '50W800冷轧无取向电工钢质量要求（QA0623隔离模拟国标）', '冷轧无取向电工钢', '50W800-QA0623', '厚度0.47mm-0.53mm，宽度900mm-1250mm', '2026版-QA0623', '2026-04-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：GB-T-SIM-2521-2026_50W800_electrical_steel_national.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_09_1', 'td_std_09_50w800_electrical', 'td_ind_p15_50', 8.0, NULL, 1, 8.3, NULL, NOW(), NOW()),
('td_si_09_2', 'td_std_09_50w800_electrical', 'td_ind_b50', NULL, 1.67, 1, NULL, NULL, NOW(), NOW()),
('td_si_09_3', 'td_std_09_50w800_electrical', 'ind004', 0.03, -0.03, 1, 0.04, -0.04, NOW(), NOW()),
('td_si_09_4', 'td_std_09_50w800_electrical', 'ind007', 210, 130, 1, 220, 120, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_09_1', 'HT-TD-09-QUAL-001', 'COIL-TD-09-QUAL-001', 'HT-TD-09-QUAL-001', 'MIDDLE', '2026-06-25 09:27:00', '021001', NULL, '冷轧无取向电工钢', '50W800-QA0623', '厚度0.50mm，宽度1200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_09_2', 'HT-TD-09-EDGE-001', 'COIL-TD-09-EDGE-001', 'HT-TD-09-EDGE-001', 'HEAD', '2026-06-25 10:27:00', '021001', NULL, '冷轧无取向电工钢', '50W800-QA0623', '厚度0.50mm，宽度1200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_09_3', 'HT-TD-09-CONC-001', 'COIL-TD-09-CONC-001', 'HT-TD-09-CONC-001', 'TAIL', '2026-06-25 11:27:00', '021001', NULL, '冷轧无取向电工钢', '50W800-QA0623', '厚度0.50mm，宽度1200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_09_4', 'HT-TD-09-REINS-001', 'COIL-TD-09-REINS-001', 'HT-TD-09-REINS-001', 'MIDDLE', '2026-06-25 12:27:00', '021001', NULL, '冷轧无取向电工钢', '50W800-QA0623', '厚度0.50mm，宽度1200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_09_5', 'HT-TD-09-UNQ-001', 'COIL-TD-09-UNQ-001', 'HT-TD-09-UNQ-001', 'HEAD', '2026-06-25 13:27:00', '021001', NULL, '冷轧无取向电工钢', '50W800-QA0623', '厚度0.50mm，宽度1200mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_09_1_1', 'td_ins_09_1', 'td_ind_p15_50', 7.8, NULL, 'system', NOW(), NOW()),
('td_iv_09_1_2', 'td_ins_09_1', 'td_ind_b50', 1.87, NULL, 'system', NOW(), NOW()),
('td_iv_09_1_3', 'td_ins_09_1', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_09_1_4', 'td_ins_09_1', 'ind007', 170, NULL, 'system', NOW(), NOW()),
('td_iv_09_2_1', 'td_ins_09_2', 'td_ind_p15_50', 8.0, NULL, 'system', NOW(), NOW()),
('td_iv_09_2_2', 'td_ins_09_2', 'td_ind_b50', 1.67, NULL, 'system', NOW(), NOW()),
('td_iv_09_2_3', 'td_ins_09_2', 'ind004', -0.03, NULL, 'system', NOW(), NOW()),
('td_iv_09_2_4', 'td_ins_09_2', 'ind007', 130, NULL, 'system', NOW(), NOW()),
('td_iv_09_3_1', 'td_ins_09_3', 'td_ind_p15_50', 8.15, NULL, 'system', NOW(), NOW()),
('td_iv_09_3_2', 'td_ins_09_3', 'td_ind_b50', 1.87, NULL, 'system', NOW(), NOW()),
('td_iv_09_3_3', 'td_ins_09_3', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_09_3_4', 'td_ins_09_3', 'ind007', 170, NULL, 'system', NOW(), NOW()),
('td_iv_09_4_1', 'td_ins_09_4', 'td_ind_p15_50', 7.8, NULL, 'system', NOW(), NOW()),
('td_iv_09_4_2', 'td_ins_09_4', 'td_ind_b50', 1.17, NULL, 'system', NOW(), NOW()),
('td_iv_09_4_3', 'td_ins_09_4', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_09_4_4', 'td_ins_09_4', 'ind007', 170, NULL, 'system', NOW(), NOW()),
('td_iv_09_5_1', 'td_ins_09_5', 'td_ind_p15_50', 8.61, NULL, 'system', NOW(), NOW()),
('td_iv_09_5_2', 'td_ins_09_5', 'td_ind_b50', 1.87, NULL, 'system', NOW(), NOW()),
('td_iv_09_5_3', 'td_ins_09_5', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_09_5_4', 'td_ins_09_5', 'ind007', 170, NULL, 'system', NOW(), NOW());
