USE ai_quality_control;

-- ============================================================
-- Inspect sample 001: HRB400E_rebar
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/GB-T-SIM-1499-2026_HRB400E_rebar_national.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_01', 'PRODUCT_VARIETY', '热轧带肋钢筋', '热轧带肋钢筋', '', 211, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_01', 'PRODUCT_GRADE', 'HRB400E-QA0623', 'HRB400E-QA0623', '', 212, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_wdev', '重量偏差', 'TD_WDEV', 'DIMENSION', '%', '理论重量差测定', '实测重量与理论重量偏差', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_01_hrb400e_rebar', 'NATIONAL', 'GB/T SIM 1499-2026-QA0623', 'HRB400E热轧带肋钢筋质量要求（QA0623隔离模拟国标）', '热轧带肋钢筋', 'HRB400E-QA0623', '公称直径12mm-32mm', '2026版-QA0623', '2026-04-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：GB-T-SIM-1499-2026_HRB400E_rebar_national.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_01_1', 'td_std_01_hrb400e_rebar', 'ind003', NULL, 400, 1, NULL, 392, NOW(), NOW()),
('td_si_01_2', 'td_std_01_hrb400e_rebar', 'ind001', NULL, 540, 1, NULL, NULL, NOW(), NOW()),
('td_si_01_3', 'td_std_01_hrb400e_rebar', 'ind002', NULL, 16, 1, NULL, 15, NOW(), NOW()),
('td_si_01_4', 'td_std_01_hrb400e_rebar', 'td_ind_wdev', 6.0, -6.0, 1, 6.5, -6.5, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_01_1', 'HT-TD-01-QUAL-001', 'COIL-TD-01-QUAL-001', 'HT-TD-01-QUAL-001', 'MIDDLE', '2026-06-23 09:03:00', '021001', NULL, '热轧带肋钢筋', 'HRB400E-QA0623', '公称直径16mm，定尺12m', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_01_2', 'HT-TD-01-EDGE-001', 'COIL-TD-01-EDGE-001', 'HT-TD-01-EDGE-001', 'HEAD', '2026-06-23 10:03:00', '021001', NULL, '热轧带肋钢筋', 'HRB400E-QA0623', '公称直径16mm，定尺12m', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_01_3', 'HT-TD-01-CONC-001', 'COIL-TD-01-CONC-001', 'HT-TD-01-CONC-001', 'TAIL', '2026-06-23 11:03:00', '021001', NULL, '热轧带肋钢筋', 'HRB400E-QA0623', '公称直径16mm，定尺12m', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_01_4', 'HT-TD-01-REINS-001', 'COIL-TD-01-REINS-001', 'HT-TD-01-REINS-001', 'MIDDLE', '2026-06-23 12:03:00', '021001', NULL, '热轧带肋钢筋', 'HRB400E-QA0623', '公称直径16mm，定尺12m', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_01_5', 'HT-TD-01-UNQ-001', 'COIL-TD-01-UNQ-001', 'HT-TD-01-UNQ-001', 'HEAD', '2026-06-23 13:03:00', '021001', NULL, '热轧带肋钢筋', 'HRB400E-QA0623', '公称直径16mm，定尺12m', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_01_1_1', 'td_ins_01_1', 'ind003', 425, NULL, 'system', NOW(), NOW()),
('td_iv_01_1_2', 'td_ins_01_1', 'ind001', 565, NULL, 'system', NOW(), NOW()),
('td_iv_01_1_3', 'td_ins_01_1', 'ind002', 18, NULL, 'system', NOW(), NOW()),
('td_iv_01_1_4', 'td_ins_01_1', 'td_ind_wdev', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_01_2_1', 'td_ins_01_2', 'ind003', 400, NULL, 'system', NOW(), NOW()),
('td_iv_01_2_2', 'td_ins_01_2', 'ind001', 540, NULL, 'system', NOW(), NOW()),
('td_iv_01_2_3', 'td_ins_01_2', 'ind002', 16, NULL, 'system', NOW(), NOW()),
('td_iv_01_2_4', 'td_ins_01_2', 'td_ind_wdev', -6.0, NULL, 'system', NOW(), NOW()),
('td_iv_01_3_1', 'td_ins_01_3', 'ind003', 396, NULL, 'system', NOW(), NOW()),
('td_iv_01_3_2', 'td_ins_01_3', 'ind001', 565, NULL, 'system', NOW(), NOW()),
('td_iv_01_3_3', 'td_ins_01_3', 'ind002', 18, NULL, 'system', NOW(), NOW()),
('td_iv_01_3_4', 'td_ins_01_3', 'td_ind_wdev', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_01_4_1', 'td_ins_01_4', 'ind003', 425, NULL, 'system', NOW(), NOW()),
('td_iv_01_4_2', 'td_ins_01_4', 'ind001', 535, NULL, 'system', NOW(), NOW()),
('td_iv_01_4_3', 'td_ins_01_4', 'ind002', 18, NULL, 'system', NOW(), NOW()),
('td_iv_01_4_4', 'td_ins_01_4', 'td_ind_wdev', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_01_5_1', 'td_ins_01_5', 'ind003', 383.99, NULL, 'system', NOW(), NOW()),
('td_iv_01_5_2', 'td_ins_01_5', 'ind001', 565, NULL, 'system', NOW(), NOW()),
('td_iv_01_5_3', 'td_ins_01_5', 'ind002', 18, NULL, 'system', NOW(), NOW()),
('td_iv_01_5_4', 'td_ins_01_5', 'td_ind_wdev', 0.0, NULL, 'system', NOW(), NOW());
