USE ai_quality_control;

-- ============================================================
-- Inspect sample 006: Q345R_pressure_vessel
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/GB-T-SIM-713-2026_Q345R_pressure_vessel_plate_national.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_06', 'PRODUCT_VARIETY', '压力容器钢板', '压力容器钢板', '', 261, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_06', 'PRODUCT_GRADE', 'Q345R-QA0623', 'Q345R-QA0623', '', 262, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_kv2', '冲击功KV2', 'TD_KV2', 'PERFORMANCE', 'J', '夏比V型缺口冲击', '低温冲击吸收能量', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_06_q345r_pressure_vessel', 'NATIONAL', 'GB/T SIM 713-2026-QA0623', 'Q345R压力容器用钢板质量要求（QA0623隔离模拟国标）', '压力容器钢板', 'Q345R-QA0623', '厚度6.00mm-40.00mm，宽度1500mm-2500mm', '2026版-QA0623', '2026-04-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：GB-T-SIM-713-2026_Q345R_pressure_vessel_plate_national.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_06_1', 'td_std_06_q345r_pressure_vessel', 'ind003', NULL, 345, 1, NULL, 335, NOW(), NOW()),
('td_si_06_2', 'td_std_06_q345r_pressure_vessel', 'ind001', 640, 510, 1, NULL, NULL, NOW(), NOW()),
('td_si_06_3', 'td_std_06_q345r_pressure_vessel', 'ind002', NULL, 21, 1, NULL, 20, NOW(), NOW()),
('td_si_06_4', 'td_std_06_q345r_pressure_vessel', 'td_ind_kv2', NULL, 34, 1, NULL, 30, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_06_1', 'HT-TD-06-QUAL-001', 'COIL-TD-06-QUAL-001', 'HT-TD-06-QUAL-001', 'MIDDLE', '2026-06-24 09:18:00', '021001', NULL, '压力容器钢板', 'Q345R-QA0623', '厚度16.00mm，宽度2000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_06_2', 'HT-TD-06-EDGE-001', 'COIL-TD-06-EDGE-001', 'HT-TD-06-EDGE-001', 'HEAD', '2026-06-24 10:18:00', '021001', NULL, '压力容器钢板', 'Q345R-QA0623', '厚度16.00mm，宽度2000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_06_3', 'HT-TD-06-CONC-001', 'COIL-TD-06-CONC-001', 'HT-TD-06-CONC-001', 'TAIL', '2026-06-24 11:18:00', '021001', NULL, '压力容器钢板', 'Q345R-QA0623', '厚度16.00mm，宽度2000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_06_4', 'HT-TD-06-REINS-001', 'COIL-TD-06-REINS-001', 'HT-TD-06-REINS-001', 'MIDDLE', '2026-06-24 12:18:00', '021001', NULL, '压力容器钢板', 'Q345R-QA0623', '厚度16.00mm，宽度2000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_06_5', 'HT-TD-06-UNQ-001', 'COIL-TD-06-UNQ-001', 'HT-TD-06-UNQ-001', 'HEAD', '2026-06-24 13:18:00', '021001', NULL, '压力容器钢板', 'Q345R-QA0623', '厚度16.00mm，宽度2000mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_06_1_1', 'td_ins_06_1', 'ind003', 370, NULL, 'system', NOW(), NOW()),
('td_iv_06_1_2', 'td_ins_06_1', 'ind001', 575, NULL, 'system', NOW(), NOW()),
('td_iv_06_1_3', 'td_ins_06_1', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_06_1_4', 'td_ins_06_1', 'td_ind_kv2', 36, NULL, 'system', NOW(), NOW()),
('td_iv_06_2_1', 'td_ins_06_2', 'ind003', 345, NULL, 'system', NOW(), NOW()),
('td_iv_06_2_2', 'td_ins_06_2', 'ind001', 510, NULL, 'system', NOW(), NOW()),
('td_iv_06_2_3', 'td_ins_06_2', 'ind002', 21, NULL, 'system', NOW(), NOW()),
('td_iv_06_2_4', 'td_ins_06_2', 'td_ind_kv2', 34, NULL, 'system', NOW(), NOW()),
('td_iv_06_3_1', 'td_ins_06_3', 'ind003', 340, NULL, 'system', NOW(), NOW()),
('td_iv_06_3_2', 'td_ins_06_3', 'ind001', 575, NULL, 'system', NOW(), NOW()),
('td_iv_06_3_3', 'td_ins_06_3', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_06_3_4', 'td_ins_06_3', 'td_ind_kv2', 36, NULL, 'system', NOW(), NOW()),
('td_iv_06_4_1', 'td_ins_06_4', 'ind003', 370, NULL, 'system', NOW(), NOW()),
('td_iv_06_4_2', 'td_ins_06_4', 'ind001', 505, NULL, 'system', NOW(), NOW()),
('td_iv_06_4_3', 'td_ins_06_4', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_06_4_4', 'td_ins_06_4', 'td_ind_kv2', 36, NULL, 'system', NOW(), NOW()),
('td_iv_06_5_1', 'td_ins_06_5', 'ind003', 324.99, NULL, 'system', NOW(), NOW()),
('td_iv_06_5_2', 'td_ins_06_5', 'ind001', 575, NULL, 'system', NOW(), NOW()),
('td_iv_06_5_3', 'td_ins_06_5', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_06_5_4', 'td_ins_06_5', 'td_ind_kv2', 36, NULL, 'system', NOW(), NOW());
