USE ai_quality_control;

-- ============================================================
-- Inspect sample 012: SPFH590_pickled
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/Q-JH-STEEL-SIM-020-2026_SPFH590_pickled_strip_enterprise.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_12', 'PRODUCT_VARIETY', '酸洗热轧钢带', '酸洗热轧钢带', '', 321, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_12', 'PRODUCT_GRADE', 'SPFH590-QA0623', 'SPFH590-QA0623', '', 322, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('ind004', '厚度公差', 'Δt', 'DIMENSION', 'mm', '千分尺测厚', '实测厚度与名义厚度之差', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_12_spfh590_pickled', 'ENTERPRISE', 'Q/JH STEEL SIM 020-2026-QA0623', 'SPFH590酸洗热轧钢带企业标准（QA0623隔离模拟企标）', '酸洗热轧钢带', 'SPFH590-QA0623', '厚度1.80mm-6.00mm，宽度800mm-1600mm', 'V2026.1-QA0623', '2026-03-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：Q-JH-STEEL-SIM-020-2026_SPFH590_pickled_strip_enterprise.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_12_1', 'td_std_12_spfh590_pickled', 'ind001', 760, 590, 1, 780, 575, NOW(), NOW()),
('td_si_12_2', 'td_std_12_spfh590_pickled', 'ind003', NULL, 420, 1, NULL, NULL, NOW(), NOW()),
('td_si_12_3', 'td_std_12_spfh590_pickled', 'ind002', NULL, 18, 1, NULL, 17, NOW(), NOW()),
('td_si_12_4', 'td_std_12_spfh590_pickled', 'ind004', 0.1, -0.1, 1, 0.12, -0.12, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_12_1', 'HT-TD-12-QUAL-001', 'COIL-TD-12-QUAL-001', 'HT-TD-12-QUAL-001', 'MIDDLE', '2026-06-25 09:36:00', '021001', NULL, '酸洗热轧钢带', 'SPFH590-QA0623', '厚度3.00mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_12_2', 'HT-TD-12-EDGE-001', 'COIL-TD-12-EDGE-001', 'HT-TD-12-EDGE-001', 'HEAD', '2026-06-25 10:36:00', '021001', NULL, '酸洗热轧钢带', 'SPFH590-QA0623', '厚度3.00mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_12_3', 'HT-TD-12-CONC-001', 'COIL-TD-12-CONC-001', 'HT-TD-12-CONC-001', 'TAIL', '2026-06-25 11:36:00', '021001', NULL, '酸洗热轧钢带', 'SPFH590-QA0623', '厚度3.00mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_12_4', 'HT-TD-12-REINS-001', 'COIL-TD-12-REINS-001', 'HT-TD-12-REINS-001', 'MIDDLE', '2026-06-25 12:36:00', '021001', NULL, '酸洗热轧钢带', 'SPFH590-QA0623', '厚度3.00mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_12_5', 'HT-TD-12-UNQ-001', 'COIL-TD-12-UNQ-001', 'HT-TD-12-UNQ-001', 'HEAD', '2026-06-25 13:36:00', '021001', NULL, '酸洗热轧钢带', 'SPFH590-QA0623', '厚度3.00mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_12_1_1', 'td_ins_12_1', 'ind001', 675, NULL, 'system', NOW(), NOW()),
('td_iv_12_1_2', 'td_ins_12_1', 'ind003', 445, NULL, 'system', NOW(), NOW()),
('td_iv_12_1_3', 'td_ins_12_1', 'ind002', 20, NULL, 'system', NOW(), NOW()),
('td_iv_12_1_4', 'td_ins_12_1', 'ind004', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_12_2_1', 'td_ins_12_2', 'ind001', 590, NULL, 'system', NOW(), NOW()),
('td_iv_12_2_2', 'td_ins_12_2', 'ind003', 420, NULL, 'system', NOW(), NOW()),
('td_iv_12_2_3', 'td_ins_12_2', 'ind002', 18, NULL, 'system', NOW(), NOW()),
('td_iv_12_2_4', 'td_ins_12_2', 'ind004', -0.1, NULL, 'system', NOW(), NOW()),
('td_iv_12_3_1', 'td_ins_12_3', 'ind001', 582.5, NULL, 'system', NOW(), NOW()),
('td_iv_12_3_2', 'td_ins_12_3', 'ind003', 445, NULL, 'system', NOW(), NOW()),
('td_iv_12_3_3', 'td_ins_12_3', 'ind002', 20, NULL, 'system', NOW(), NOW()),
('td_iv_12_3_4', 'td_ins_12_3', 'ind004', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_12_4_1', 'td_ins_12_4', 'ind001', 675, NULL, 'system', NOW(), NOW()),
('td_iv_12_4_2', 'td_ins_12_4', 'ind003', 415, NULL, 'system', NOW(), NOW()),
('td_iv_12_4_3', 'td_ins_12_4', 'ind002', 20, NULL, 'system', NOW(), NOW()),
('td_iv_12_4_4', 'td_ins_12_4', 'ind004', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_12_5_1', 'td_ins_12_5', 'ind001', 559.99, NULL, 'system', NOW(), NOW()),
('td_iv_12_5_2', 'td_ins_12_5', 'ind003', 445, NULL, 'system', NOW(), NOW()),
('td_iv_12_5_3', 'td_ins_12_5', 'ind002', 20, NULL, 'system', NOW(), NOW()),
('td_iv_12_5_4', 'td_ins_12_5', 'ind004', 0.0, NULL, 'system', NOW(), NOW());
