USE ai_quality_control;

-- ============================================================
-- Inspect sample 017: HC340LA_customer_HDQC
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/CUST-HDQC-SIM-2026-HC340LA_customer_agreement.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_17', 'PRODUCT_VARIETY', '冷轧低合金高强钢板', '冷轧低合金高强钢板', '', 371, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_17', 'PRODUCT_GRADE', 'HC340LA-QA0623', 'HC340LA-QA0623', '', 372, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW()),
('td_cust_17', 'QC_CUSTOMER', 'TD-CUST-HDQC', '华东汽车配件有限公司', '', 373, 1, 0, '测试包：客户协议检验记录样例', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('ind004', '厚度公差', 'Δt', 'DIMENSION', 'mm', '千分尺测厚', '实测厚度与名义厚度之差', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_17_hc340la_customer_hdqc', 'CUSTOMER', 'AGREEMENT HDQC-SIM-2026-002-QA0623', '华东汽车配件有限公司HC340LA冷轧结构板供货质量协议（QA0623隔离模拟客户协议）', '冷轧低合金高强钢板', 'HC340LA-QA0623', '厚度0.90mm-2.00mm，宽度900mm-1450mm', '协议V1.0-QA0623', '2026-03-01', '2026-12-31', 'PUBLISHED', 'TD-CUST-HDQC', '来源PDF：CUST-HDQC-SIM-2026-HC340LA_customer_agreement.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_17_1', 'td_std_17_hc340la_customer_hdqc', 'ind003', 410, 340, 1, 420, 330, NOW(), NOW()),
('td_si_17_2', 'td_std_17_hc340la_customer_hdqc', 'ind001', 500, 420, 1, NULL, NULL, NOW(), NOW()),
('td_si_17_3', 'td_std_17_hc340la_customer_hdqc', 'ind002', NULL, 23, 1, NULL, 22, NOW(), NOW()),
('td_si_17_4', 'td_std_17_hc340la_customer_hdqc', 'ind004', 0.05, -0.05, 1, 0.06, -0.06, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_17_1', 'HT-TD-17-QUAL-001', 'COIL-TD-17-QUAL-001', 'HT-TD-17-QUAL-001', 'MIDDLE', '2026-06-27 09:51:00', '021001', 'TD-CUST-HDQC', '冷轧低合金高强钢板', 'HC340LA-QA0623', '厚度1.20mm，宽度1200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_17_2', 'HT-TD-17-EDGE-001', 'COIL-TD-17-EDGE-001', 'HT-TD-17-EDGE-001', 'HEAD', '2026-06-27 10:51:00', '021001', 'TD-CUST-HDQC', '冷轧低合金高强钢板', 'HC340LA-QA0623', '厚度1.20mm，宽度1200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_17_3', 'HT-TD-17-CONC-001', 'COIL-TD-17-CONC-001', 'HT-TD-17-CONC-001', 'TAIL', '2026-06-27 11:51:00', '021001', 'TD-CUST-HDQC', '冷轧低合金高强钢板', 'HC340LA-QA0623', '厚度1.20mm，宽度1200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_17_4', 'HT-TD-17-REINS-001', 'COIL-TD-17-REINS-001', 'HT-TD-17-REINS-001', 'MIDDLE', '2026-06-27 12:51:00', '021001', 'TD-CUST-HDQC', '冷轧低合金高强钢板', 'HC340LA-QA0623', '厚度1.20mm，宽度1200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_17_5', 'HT-TD-17-UNQ-001', 'COIL-TD-17-UNQ-001', 'HT-TD-17-UNQ-001', 'HEAD', '2026-06-27 13:51:00', '021001', 'TD-CUST-HDQC', '冷轧低合金高强钢板', 'HC340LA-QA0623', '厚度1.20mm，宽度1200mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_17_1_1', 'td_ins_17_1', 'ind003', 375, NULL, 'system', NOW(), NOW()),
('td_iv_17_1_2', 'td_ins_17_1', 'ind001', 460, NULL, 'system', NOW(), NOW()),
('td_iv_17_1_3', 'td_ins_17_1', 'ind002', 25, NULL, 'system', NOW(), NOW()),
('td_iv_17_1_4', 'td_ins_17_1', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_17_2_1', 'td_ins_17_2', 'ind003', 340, NULL, 'system', NOW(), NOW()),
('td_iv_17_2_2', 'td_ins_17_2', 'ind001', 420, NULL, 'system', NOW(), NOW()),
('td_iv_17_2_3', 'td_ins_17_2', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_17_2_4', 'td_ins_17_2', 'ind004', -0.05, NULL, 'system', NOW(), NOW()),
('td_iv_17_3_1', 'td_ins_17_3', 'ind003', 335, NULL, 'system', NOW(), NOW()),
('td_iv_17_3_2', 'td_ins_17_3', 'ind001', 460, NULL, 'system', NOW(), NOW()),
('td_iv_17_3_3', 'td_ins_17_3', 'ind002', 25, NULL, 'system', NOW(), NOW()),
('td_iv_17_3_4', 'td_ins_17_3', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_17_4_1', 'td_ins_17_4', 'ind003', 375, NULL, 'system', NOW(), NOW()),
('td_iv_17_4_2', 'td_ins_17_4', 'ind001', 415, NULL, 'system', NOW(), NOW()),
('td_iv_17_4_3', 'td_ins_17_4', 'ind002', 25, NULL, 'system', NOW(), NOW()),
('td_iv_17_4_4', 'td_ins_17_4', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_17_5_1', 'td_ins_17_5', 'ind003', 319.99, NULL, 'system', NOW(), NOW()),
('td_iv_17_5_2', 'td_ins_17_5', 'ind001', 460, NULL, 'system', NOW(), NOW()),
('td_iv_17_5_3', 'td_ins_17_5', 'ind002', 25, NULL, 'system', NOW(), NOW()),
('td_iv_17_5_4', 'td_ins_17_5', 'ind004', 0.00, NULL, 'system', NOW(), NOW());
