USE ai_quality_control;

-- ============================================================
-- Inspect sample 005: 06Cr19Ni10_stainless
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/GB-T-SIM-4237-2026_06Cr19Ni10_stainless_sheet_national.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_05', 'PRODUCT_VARIETY', '冷轧不锈钢板', '冷轧不锈钢板', '', 251, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_05', 'PRODUCT_GRADE', '06Cr19Ni10-QA0623', '06Cr19Ni10-QA0623', '', 252, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_cr', '铬', 'TD_CR', 'COMPOSITION', '%', '熔炼分析', '铬元素质量分数', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_ni', '镍', 'TD_NI', 'COMPOSITION', '%', '熔炼分析', '镍元素质量分数', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_05_06cr19ni10_stainless', 'NATIONAL', 'GB/T SIM 4237-2026-QA0623', '06Cr19Ni10不锈钢冷轧钢板质量要求（QA0623隔离模拟国标）', '冷轧不锈钢板', '06Cr19Ni10-QA0623', '厚度0.80mm-6.00mm，宽度800mm-1600mm', '2026版-QA0623', '2026-04-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：GB-T-SIM-4237-2026_06Cr19Ni10_stainless_sheet_national.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_05_1', 'td_std_05_06cr19ni10_stainless', 'td_ind_cr', 20.0, 18.0, 1, 20.2, 17.8, NOW(), NOW()),
('td_si_05_2', 'td_std_05_06cr19ni10_stainless', 'td_ind_ni', 11.0, 8.0, 1, NULL, NULL, NOW(), NOW()),
('td_si_05_3', 'td_std_05_06cr19ni10_stainless', 'ind001', NULL, 520, 1, NULL, 510, NOW(), NOW()),
('td_si_05_4', 'td_std_05_06cr19ni10_stainless', 'ind002', NULL, 40, 1, NULL, 38, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_05_1', 'HT-TD-05-QUAL-001', 'COIL-TD-05-QUAL-001', 'HT-TD-05-QUAL-001', 'MIDDLE', '2026-06-24 09:15:00', '021001', NULL, '冷轧不锈钢板', '06Cr19Ni10-QA0623', '厚度2.00mm，宽度1219mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_05_2', 'HT-TD-05-EDGE-001', 'COIL-TD-05-EDGE-001', 'HT-TD-05-EDGE-001', 'HEAD', '2026-06-24 10:15:00', '021001', NULL, '冷轧不锈钢板', '06Cr19Ni10-QA0623', '厚度2.00mm，宽度1219mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_05_3', 'HT-TD-05-CONC-001', 'COIL-TD-05-CONC-001', 'HT-TD-05-CONC-001', 'TAIL', '2026-06-24 11:15:00', '021001', NULL, '冷轧不锈钢板', '06Cr19Ni10-QA0623', '厚度2.00mm，宽度1219mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_05_4', 'HT-TD-05-REINS-001', 'COIL-TD-05-REINS-001', 'HT-TD-05-REINS-001', 'MIDDLE', '2026-06-24 12:15:00', '021001', NULL, '冷轧不锈钢板', '06Cr19Ni10-QA0623', '厚度2.00mm，宽度1219mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_05_5', 'HT-TD-05-UNQ-001', 'COIL-TD-05-UNQ-001', 'HT-TD-05-UNQ-001', 'HEAD', '2026-06-24 13:15:00', '021001', NULL, '冷轧不锈钢板', '06Cr19Ni10-QA0623', '厚度2.00mm，宽度1219mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_05_1_1', 'td_ins_05_1', 'td_ind_cr', 19.0, NULL, 'system', NOW(), NOW()),
('td_iv_05_1_2', 'td_ins_05_1', 'td_ind_ni', 9.5, NULL, 'system', NOW(), NOW()),
('td_iv_05_1_3', 'td_ins_05_1', 'ind001', 545, NULL, 'system', NOW(), NOW()),
('td_iv_05_1_4', 'td_ins_05_1', 'ind002', 42, NULL, 'system', NOW(), NOW()),
('td_iv_05_2_1', 'td_ins_05_2', 'td_ind_cr', 18.0, NULL, 'system', NOW(), NOW()),
('td_iv_05_2_2', 'td_ins_05_2', 'td_ind_ni', 8.0, NULL, 'system', NOW(), NOW()),
('td_iv_05_2_3', 'td_ins_05_2', 'ind001', 520, NULL, 'system', NOW(), NOW()),
('td_iv_05_2_4', 'td_ins_05_2', 'ind002', 40, NULL, 'system', NOW(), NOW()),
('td_iv_05_3_1', 'td_ins_05_3', 'td_ind_cr', 17.9, NULL, 'system', NOW(), NOW()),
('td_iv_05_3_2', 'td_ins_05_3', 'td_ind_ni', 9.5, NULL, 'system', NOW(), NOW()),
('td_iv_05_3_3', 'td_ins_05_3', 'ind001', 545, NULL, 'system', NOW(), NOW()),
('td_iv_05_3_4', 'td_ins_05_3', 'ind002', 42, NULL, 'system', NOW(), NOW()),
('td_iv_05_4_1', 'td_ins_05_4', 'td_ind_cr', 19.0, NULL, 'system', NOW(), NOW()),
('td_iv_05_4_2', 'td_ins_05_4', 'td_ind_ni', 7.5, NULL, 'system', NOW(), NOW()),
('td_iv_05_4_3', 'td_ins_05_4', 'ind001', 545, NULL, 'system', NOW(), NOW()),
('td_iv_05_4_4', 'td_ins_05_4', 'ind002', 42, NULL, 'system', NOW(), NOW()),
('td_iv_05_5_1', 'td_ins_05_5', 'td_ind_cr', 17.59, NULL, 'system', NOW(), NOW()),
('td_iv_05_5_2', 'td_ins_05_5', 'td_ind_ni', 9.5, NULL, 'system', NOW(), NOW()),
('td_iv_05_5_3', 'td_ins_05_5', 'ind001', 545, NULL, 'system', NOW(), NOW()),
('td_iv_05_5_4', 'td_ins_05_5', 'ind002', 42, NULL, 'system', NOW(), NOW());
