USE ai_quality_control;

-- ============================================================
-- Inspect sample 010: 60Si2Mn_spring
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/GB-T-SIM-1222-2026_60Si2Mn_spring_flat_steel_national.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_10', 'PRODUCT_VARIETY', '热轧弹簧扁钢', '热轧弹簧扁钢', '', 301, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_10', 'PRODUCT_GRADE', '60Si2Mn-QA0623', '60Si2Mn-QA0623', '', 302, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind007', '硬度', 'HV', 'PERFORMANCE', 'HV', 'GB/T 4340.1', '维氏硬度', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_c', '碳', 'TD_C', 'COMPOSITION', '%', '熔炼分析', '碳元素质量分数', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_mn', '锰', 'TD_MN', 'COMPOSITION', '%', '熔炼分析', '锰元素质量分数', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_si', '硅', 'TD_SI', 'COMPOSITION', '%', '熔炼分析', '硅元素质量分数', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_10_60si2mn_spring', 'NATIONAL', 'GB/T SIM 1222-2026-QA0623', '60Si2Mn热轧弹簧扁钢质量要求（QA0623隔离模拟国标）', '热轧弹簧扁钢', '60Si2Mn-QA0623', '厚度5.00mm-30.00mm，宽度40mm-160mm', '2026版-QA0623', '2026-04-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：GB-T-SIM-1222-2026_60Si2Mn_spring_flat_steel_national.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_10_1', 'td_std_10_60si2mn_spring', 'td_ind_c', 0.64, 0.56, 1, 0.65, 0.55, NOW(), NOW()),
('td_si_10_2', 'td_std_10_60si2mn_spring', 'td_ind_si', 2.0, 1.5, 1, NULL, NULL, NOW(), NOW()),
('td_si_10_3', 'td_std_10_60si2mn_spring', 'td_ind_mn', 0.9, 0.6, 1, 0.92, 0.58, NOW(), NOW()),
('td_si_10_4', 'td_std_10_60si2mn_spring', 'ind007', 380, 300, 1, 390, 290, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_10_1', 'HT-TD-10-QUAL-001', 'COIL-TD-10-QUAL-001', 'HT-TD-10-QUAL-001', 'MIDDLE', '2026-06-25 09:30:00', '021001', NULL, '热轧弹簧扁钢', '60Si2Mn-QA0623', '厚度12.00mm，宽度80mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_10_2', 'HT-TD-10-EDGE-001', 'COIL-TD-10-EDGE-001', 'HT-TD-10-EDGE-001', 'HEAD', '2026-06-25 10:30:00', '021001', NULL, '热轧弹簧扁钢', '60Si2Mn-QA0623', '厚度12.00mm，宽度80mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_10_3', 'HT-TD-10-CONC-001', 'COIL-TD-10-CONC-001', 'HT-TD-10-CONC-001', 'TAIL', '2026-06-25 11:30:00', '021001', NULL, '热轧弹簧扁钢', '60Si2Mn-QA0623', '厚度12.00mm，宽度80mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_10_4', 'HT-TD-10-REINS-001', 'COIL-TD-10-REINS-001', 'HT-TD-10-REINS-001', 'MIDDLE', '2026-06-25 12:30:00', '021001', NULL, '热轧弹簧扁钢', '60Si2Mn-QA0623', '厚度12.00mm，宽度80mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_10_5', 'HT-TD-10-UNQ-001', 'COIL-TD-10-UNQ-001', 'HT-TD-10-UNQ-001', 'HEAD', '2026-06-25 13:30:00', '021001', NULL, '热轧弹簧扁钢', '60Si2Mn-QA0623', '厚度12.00mm，宽度80mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_10_1_1', 'td_ins_10_1', 'td_ind_c', 0.60, NULL, 'system', NOW(), NOW()),
('td_iv_10_1_2', 'td_ins_10_1', 'td_ind_si', 1.75, NULL, 'system', NOW(), NOW()),
('td_iv_10_1_3', 'td_ins_10_1', 'td_ind_mn', 0.75, NULL, 'system', NOW(), NOW()),
('td_iv_10_1_4', 'td_ins_10_1', 'ind007', 340, NULL, 'system', NOW(), NOW()),
('td_iv_10_2_1', 'td_ins_10_2', 'td_ind_c', 0.56, NULL, 'system', NOW(), NOW()),
('td_iv_10_2_2', 'td_ins_10_2', 'td_ind_si', 1.5, NULL, 'system', NOW(), NOW()),
('td_iv_10_2_3', 'td_ins_10_2', 'td_ind_mn', 0.6, NULL, 'system', NOW(), NOW()),
('td_iv_10_2_4', 'td_ins_10_2', 'ind007', 300, NULL, 'system', NOW(), NOW()),
('td_iv_10_3_1', 'td_ins_10_3', 'td_ind_c', 0.555, NULL, 'system', NOW(), NOW()),
('td_iv_10_3_2', 'td_ins_10_3', 'td_ind_si', 1.75, NULL, 'system', NOW(), NOW()),
('td_iv_10_3_3', 'td_ins_10_3', 'td_ind_mn', 0.75, NULL, 'system', NOW(), NOW()),
('td_iv_10_3_4', 'td_ins_10_3', 'ind007', 340, NULL, 'system', NOW(), NOW()),
('td_iv_10_4_1', 'td_ins_10_4', 'td_ind_c', 0.60, NULL, 'system', NOW(), NOW()),
('td_iv_10_4_2', 'td_ins_10_4', 'td_ind_si', 1.0, NULL, 'system', NOW(), NOW()),
('td_iv_10_4_3', 'td_ins_10_4', 'td_ind_mn', 0.75, NULL, 'system', NOW(), NOW()),
('td_iv_10_4_4', 'td_ins_10_4', 'ind007', 340, NULL, 'system', NOW(), NOW()),
('td_iv_10_5_1', 'td_ins_10_5', 'td_ind_c', 0.53, NULL, 'system', NOW(), NOW()),
('td_iv_10_5_2', 'td_ins_10_5', 'td_ind_si', 1.75, NULL, 'system', NOW(), NOW()),
('td_iv_10_5_3', 'td_ins_10_5', 'td_ind_mn', 0.75, NULL, 'system', NOW(), NOW()),
('td_iv_10_5_4', 'td_ins_10_5', 'ind007', 340, NULL, 'system', NOW(), NOW());
