USE ai_quality_control;

-- ============================================================
-- Inspect sample 016: Q235B_customer_XNJC
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/CUST-XNJC-SIM-2026-Q235B_customer_agreement.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_16', 'PRODUCT_VARIETY', '冷轧板', '冷轧板', '', 361, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_16', 'PRODUCT_GRADE', 'Q235B-QA0623', 'Q235B-QA0623', '', 362, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW()),
('td_cust_16', 'QC_CUSTOMER', 'TD-CUST-XNJC', '西南建材集团', '', 363, 1, 0, '测试包：客户协议检验记录样例', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('ind004', '厚度公差', 'Δt', 'DIMENSION', 'mm', '千分尺测厚', '实测厚度与名义厚度之差', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_16_q235b_customer_xnjc', 'CUSTOMER', 'AGREEMENT XNJC-SIM-2026-001-QA0623', '西南建材集团Q235B冷轧板供货质量协议（QA0623隔离模拟客户协议）', '冷轧板', 'Q235B-QA0623', '厚度0.80mm-2.50mm，宽度800mm-1250mm', '协议V1.0-QA0623', '2026-02-01', '2026-12-31', 'PUBLISHED', 'TD-CUST-XNJC', '来源PDF：CUST-XNJC-SIM-2026-Q235B_customer_agreement.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_16_1', 'td_std_16_q235b_customer_xnjc', 'ind001', 505, 375, 1, 510, 370, NOW(), NOW()),
('td_si_16_2', 'td_std_16_q235b_customer_xnjc', 'ind002', NULL, 27, 1, NULL, NULL, NOW(), NOW()),
('td_si_16_3', 'td_std_16_q235b_customer_xnjc', 'ind003', 360, 235, 1, 370, 225, NOW(), NOW()),
('td_si_16_4', 'td_std_16_q235b_customer_xnjc', 'ind004', 0.08, -0.08, 1, 0.1, -0.1, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_16_1', 'HT-TD-16-QUAL-001', 'COIL-TD-16-QUAL-001', 'HT-TD-16-QUAL-001', 'MIDDLE', '2026-06-26 09:48:00', '021001', 'TD-CUST-XNJC', '冷轧板', 'Q235B-QA0623', '厚度1.20mm，宽度1000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_16_2', 'HT-TD-16-EDGE-001', 'COIL-TD-16-EDGE-001', 'HT-TD-16-EDGE-001', 'HEAD', '2026-06-26 10:48:00', '021001', 'TD-CUST-XNJC', '冷轧板', 'Q235B-QA0623', '厚度1.20mm，宽度1000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_16_3', 'HT-TD-16-CONC-001', 'COIL-TD-16-CONC-001', 'HT-TD-16-CONC-001', 'TAIL', '2026-06-26 11:48:00', '021001', 'TD-CUST-XNJC', '冷轧板', 'Q235B-QA0623', '厚度1.20mm，宽度1000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_16_4', 'HT-TD-16-REINS-001', 'COIL-TD-16-REINS-001', 'HT-TD-16-REINS-001', 'MIDDLE', '2026-06-26 12:48:00', '021001', 'TD-CUST-XNJC', '冷轧板', 'Q235B-QA0623', '厚度1.20mm，宽度1000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_16_5', 'HT-TD-16-UNQ-001', 'COIL-TD-16-UNQ-001', 'HT-TD-16-UNQ-001', 'HEAD', '2026-06-26 13:48:00', '021001', 'TD-CUST-XNJC', '冷轧板', 'Q235B-QA0623', '厚度1.20mm，宽度1000mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_16_1_1', 'td_ins_16_1', 'ind001', 440, NULL, 'system', NOW(), NOW()),
('td_iv_16_1_2', 'td_ins_16_1', 'ind002', 29, NULL, 'system', NOW(), NOW()),
('td_iv_16_1_3', 'td_ins_16_1', 'ind003', 297.5, NULL, 'system', NOW(), NOW()),
('td_iv_16_1_4', 'td_ins_16_1', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_16_2_1', 'td_ins_16_2', 'ind001', 375, NULL, 'system', NOW(), NOW()),
('td_iv_16_2_2', 'td_ins_16_2', 'ind002', 27, NULL, 'system', NOW(), NOW()),
('td_iv_16_2_3', 'td_ins_16_2', 'ind003', 235, NULL, 'system', NOW(), NOW()),
('td_iv_16_2_4', 'td_ins_16_2', 'ind004', -0.08, NULL, 'system', NOW(), NOW()),
('td_iv_16_3_1', 'td_ins_16_3', 'ind001', 372.5, NULL, 'system', NOW(), NOW()),
('td_iv_16_3_2', 'td_ins_16_3', 'ind002', 29, NULL, 'system', NOW(), NOW()),
('td_iv_16_3_3', 'td_ins_16_3', 'ind003', 297.5, NULL, 'system', NOW(), NOW()),
('td_iv_16_3_4', 'td_ins_16_3', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_16_4_1', 'td_ins_16_4', 'ind001', 440, NULL, 'system', NOW(), NOW()),
('td_iv_16_4_2', 'td_ins_16_4', 'ind002', 26.5, NULL, 'system', NOW(), NOW()),
('td_iv_16_4_3', 'td_ins_16_4', 'ind003', 297.5, NULL, 'system', NOW(), NOW()),
('td_iv_16_4_4', 'td_ins_16_4', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_16_5_1', 'td_ins_16_5', 'ind001', 364.99, NULL, 'system', NOW(), NOW()),
('td_iv_16_5_2', 'td_ins_16_5', 'ind002', 29, NULL, 'system', NOW(), NOW()),
('td_iv_16_5_3', 'td_ins_16_5', 'ind003', 297.5, NULL, 'system', NOW(), NOW()),
('td_iv_16_5_4', 'td_ins_16_5', 'ind004', 0.00, NULL, 'system', NOW(), NOW());
