USE ai_quality_control;

-- ============================================================
-- Inspect sample 002: Q235B_cold_rolled_national
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/GB-T-SIM-912-2026_Q235B_cold_rolled_sheet_national.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_02', 'PRODUCT_VARIETY', '冷轧板', '冷轧板', '', 221, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_02', 'PRODUCT_GRADE', 'Q235B-QA0623', 'Q235B-QA0623', '', 222, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('ind004', '厚度公差', 'Δt', 'DIMENSION', 'mm', '千分尺测厚', '实测厚度与名义厚度之差', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_02_q235b_cold_rolled_national', 'NATIONAL', 'GB/T SIM 912-2026-QA0623', '碳素结构钢冷轧薄板及钢带质量要求（QA0623隔离模拟国标）', '冷轧板', 'Q235B-QA0623', '厚度0.50mm-3.00mm，宽度600mm-1500mm', '2026版-QA0623', '2026-03-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：GB-T-SIM-912-2026_Q235B_cold_rolled_sheet_national.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_02_1', 'td_std_02_q235b_cold_rolled_national', 'ind001', 510, 370, 1, 520, 360, NOW(), NOW()),
('td_si_02_2', 'td_std_02_q235b_cold_rolled_national', 'ind002', NULL, 26, 1, NULL, NULL, NOW(), NOW()),
('td_si_02_3', 'td_std_02_q235b_cold_rolled_national', 'ind003', NULL, 235, 1, NULL, 225, NOW(), NOW()),
('td_si_02_4', 'td_std_02_q235b_cold_rolled_national', 'ind004', 0.12, -0.12, 1, 0.15, -0.15, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_02_1', 'HT-TD-02-QUAL-001', 'COIL-TD-02-QUAL-001', 'HT-TD-02-QUAL-001', 'MIDDLE', '2026-06-23 09:06:00', '021001', NULL, '冷轧板', 'Q235B-QA0623', '厚度1.50mm，宽度1000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_02_2', 'HT-TD-02-EDGE-001', 'COIL-TD-02-EDGE-001', 'HT-TD-02-EDGE-001', 'HEAD', '2026-06-23 10:06:00', '021001', NULL, '冷轧板', 'Q235B-QA0623', '厚度1.50mm，宽度1000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_02_3', 'HT-TD-02-CONC-001', 'COIL-TD-02-CONC-001', 'HT-TD-02-CONC-001', 'TAIL', '2026-06-23 11:06:00', '021001', NULL, '冷轧板', 'Q235B-QA0623', '厚度1.50mm，宽度1000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_02_4', 'HT-TD-02-REINS-001', 'COIL-TD-02-REINS-001', 'HT-TD-02-REINS-001', 'MIDDLE', '2026-06-23 12:06:00', '021001', NULL, '冷轧板', 'Q235B-QA0623', '厚度1.50mm，宽度1000mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_02_5', 'HT-TD-02-UNQ-001', 'COIL-TD-02-UNQ-001', 'HT-TD-02-UNQ-001', 'HEAD', '2026-06-23 13:06:00', '021001', NULL, '冷轧板', 'Q235B-QA0623', '厚度1.50mm，宽度1000mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_02_1_1', 'td_ins_02_1', 'ind001', 440, NULL, 'system', NOW(), NOW()),
('td_iv_02_1_2', 'td_ins_02_1', 'ind002', 28, NULL, 'system', NOW(), NOW()),
('td_iv_02_1_3', 'td_ins_02_1', 'ind003', 260, NULL, 'system', NOW(), NOW()),
('td_iv_02_1_4', 'td_ins_02_1', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_02_2_1', 'td_ins_02_2', 'ind001', 370, NULL, 'system', NOW(), NOW()),
('td_iv_02_2_2', 'td_ins_02_2', 'ind002', 26, NULL, 'system', NOW(), NOW()),
('td_iv_02_2_3', 'td_ins_02_2', 'ind003', 235, NULL, 'system', NOW(), NOW()),
('td_iv_02_2_4', 'td_ins_02_2', 'ind004', -0.12, NULL, 'system', NOW(), NOW()),
('td_iv_02_3_1', 'td_ins_02_3', 'ind001', 365, NULL, 'system', NOW(), NOW()),
('td_iv_02_3_2', 'td_ins_02_3', 'ind002', 28, NULL, 'system', NOW(), NOW()),
('td_iv_02_3_3', 'td_ins_02_3', 'ind003', 260, NULL, 'system', NOW(), NOW()),
('td_iv_02_3_4', 'td_ins_02_3', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_02_4_1', 'td_ins_02_4', 'ind001', 440, NULL, 'system', NOW(), NOW()),
('td_iv_02_4_2', 'td_ins_02_4', 'ind002', 25.5, NULL, 'system', NOW(), NOW()),
('td_iv_02_4_3', 'td_ins_02_4', 'ind003', 260, NULL, 'system', NOW(), NOW()),
('td_iv_02_4_4', 'td_ins_02_4', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_02_5_1', 'td_ins_02_5', 'ind001', 349.99, NULL, 'system', NOW(), NOW()),
('td_iv_02_5_2', 'td_ins_02_5', 'ind002', 28, NULL, 'system', NOW(), NOW()),
('td_iv_02_5_3', 'td_ins_02_5', 'ind003', 260, NULL, 'system', NOW(), NOW()),
('td_iv_02_5_4', 'td_ins_02_5', 'ind004', 0.00, NULL, 'system', NOW(), NOW());
