USE ai_quality_control;

-- ============================================================
-- Inspect sample 019: AH36_customer_ZYSHIP
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/CUST-ZYSHIP-SIM-2026-AH36_customer_agreement.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_19', 'PRODUCT_VARIETY', '船体结构钢板', '船体结构钢板', '', 391, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_19', 'PRODUCT_GRADE', 'AH36-QA0623', 'AH36-QA0623', '', 392, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW()),
('td_cust_19', 'QC_CUSTOMER', 'TD-CUST-ZYSHIP', '中远船务', '', 393, 1, 0, '测试包：客户协议检验记录样例', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_kv2', '冲击功KV2', 'TD_KV2', 'PERFORMANCE', 'J', '夏比V型缺口冲击', '低温冲击吸收能量', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_19_ah36_customer_zyship', 'CUSTOMER', 'AGREEMENT ZYSHIP-SIM-2026-004-QA0623', '中远船务AH36船体结构钢板供货质量协议（QA0623隔离模拟客户协议）', '船体结构钢板', 'AH36-QA0623', '厚度8.00mm-40.00mm，宽度1500mm-3000mm', '协议V1.0-QA0623', '2026-03-01', '2026-12-31', 'PUBLISHED', 'TD-CUST-ZYSHIP', '来源PDF：CUST-ZYSHIP-SIM-2026-AH36_customer_agreement.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_19_1', 'td_std_19_ah36_customer_zyship', 'ind003', NULL, 355, 1, NULL, 345, NOW(), NOW()),
('td_si_19_2', 'td_std_19_ah36_customer_zyship', 'ind001', 620, 490, 1, NULL, NULL, NOW(), NOW()),
('td_si_19_3', 'td_std_19_ah36_customer_zyship', 'ind002', NULL, 21, 1, NULL, 20, NOW(), NOW()),
('td_si_19_4', 'td_std_19_ah36_customer_zyship', 'td_ind_kv2', NULL, 34, 1, NULL, 30, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_19_1', 'HT-TD-19-QUAL-001', 'COIL-TD-19-QUAL-001', 'HT-TD-19-QUAL-001', 'MIDDLE', '2026-06-27 09:57:00', '021001', 'TD-CUST-ZYSHIP', '船体结构钢板', 'AH36-QA0623', '厚度18.00mm，宽度2200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_19_2', 'HT-TD-19-EDGE-001', 'COIL-TD-19-EDGE-001', 'HT-TD-19-EDGE-001', 'HEAD', '2026-06-27 10:57:00', '021001', 'TD-CUST-ZYSHIP', '船体结构钢板', 'AH36-QA0623', '厚度18.00mm，宽度2200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_19_3', 'HT-TD-19-CONC-001', 'COIL-TD-19-CONC-001', 'HT-TD-19-CONC-001', 'TAIL', '2026-06-27 11:57:00', '021001', 'TD-CUST-ZYSHIP', '船体结构钢板', 'AH36-QA0623', '厚度18.00mm，宽度2200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_19_4', 'HT-TD-19-REINS-001', 'COIL-TD-19-REINS-001', 'HT-TD-19-REINS-001', 'MIDDLE', '2026-06-27 12:57:00', '021001', 'TD-CUST-ZYSHIP', '船体结构钢板', 'AH36-QA0623', '厚度18.00mm，宽度2200mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_19_5', 'HT-TD-19-UNQ-001', 'COIL-TD-19-UNQ-001', 'HT-TD-19-UNQ-001', 'HEAD', '2026-06-27 13:57:00', '021001', 'TD-CUST-ZYSHIP', '船体结构钢板', 'AH36-QA0623', '厚度18.00mm，宽度2200mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_19_1_1', 'td_ins_19_1', 'ind003', 380, NULL, 'system', NOW(), NOW()),
('td_iv_19_1_2', 'td_ins_19_1', 'ind001', 555, NULL, 'system', NOW(), NOW()),
('td_iv_19_1_3', 'td_ins_19_1', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_19_1_4', 'td_ins_19_1', 'td_ind_kv2', 36, NULL, 'system', NOW(), NOW()),
('td_iv_19_2_1', 'td_ins_19_2', 'ind003', 355, NULL, 'system', NOW(), NOW()),
('td_iv_19_2_2', 'td_ins_19_2', 'ind001', 490, NULL, 'system', NOW(), NOW()),
('td_iv_19_2_3', 'td_ins_19_2', 'ind002', 21, NULL, 'system', NOW(), NOW()),
('td_iv_19_2_4', 'td_ins_19_2', 'td_ind_kv2', 34, NULL, 'system', NOW(), NOW()),
('td_iv_19_3_1', 'td_ins_19_3', 'ind003', 350, NULL, 'system', NOW(), NOW()),
('td_iv_19_3_2', 'td_ins_19_3', 'ind001', 555, NULL, 'system', NOW(), NOW()),
('td_iv_19_3_3', 'td_ins_19_3', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_19_3_4', 'td_ins_19_3', 'td_ind_kv2', 36, NULL, 'system', NOW(), NOW()),
('td_iv_19_4_1', 'td_ins_19_4', 'ind003', 380, NULL, 'system', NOW(), NOW()),
('td_iv_19_4_2', 'td_ins_19_4', 'ind001', 485, NULL, 'system', NOW(), NOW()),
('td_iv_19_4_3', 'td_ins_19_4', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_19_4_4', 'td_ins_19_4', 'td_ind_kv2', 36, NULL, 'system', NOW(), NOW()),
('td_iv_19_5_1', 'td_ins_19_5', 'ind003', 334.99, NULL, 'system', NOW(), NOW()),
('td_iv_19_5_2', 'td_ins_19_5', 'ind001', 555, NULL, 'system', NOW(), NOW()),
('td_iv_19_5_3', 'td_ins_19_5', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_19_5_4', 'td_ins_19_5', 'td_ind_kv2', 36, NULL, 'system', NOW(), NOW());
