USE ai_quality_control;

-- ============================================================
-- Inspect sample 008: DC04_deep_drawing
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/GB-T-SIM-5213-2026_DC04_deep_drawing_sheet_national.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_08', 'PRODUCT_VARIETY', '深冲冷轧板', '深冲冷轧板', '', 281, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_08', 'PRODUCT_GRADE', 'DC04-QA0623', 'DC04-QA0623', '', 282, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('ind008', 'n值', 'n', 'PERFORMANCE', '-', '拉伸应变硬化指数', '成形性能指标', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_08_dc04_deep_drawing', 'NATIONAL', 'GB/T SIM 5213-2026-QA0623', 'DC04深冲冷轧板质量要求（QA0623隔离模拟国标）', '深冲冷轧板', 'DC04-QA0623', '厚度0.50mm-2.00mm，宽度800mm-1500mm', '2026版-QA0623', '2026-04-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：GB-T-SIM-5213-2026_DC04_deep_drawing_sheet_national.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_08_1', 'td_std_08_dc04_deep_drawing', 'ind003', 210, 140, 1, 220, 130, NOW(), NOW()),
('td_si_08_2', 'td_std_08_dc04_deep_drawing', 'ind001', 350, 270, 1, NULL, NULL, NOW(), NOW()),
('td_si_08_3', 'td_std_08_dc04_deep_drawing', 'ind002', NULL, 38, 1, NULL, 36, NOW(), NOW()),
('td_si_08_4', 'td_std_08_dc04_deep_drawing', 'ind008', NULL, 0.18, 1, NULL, 0.16, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_08_1', 'HT-TD-08-QUAL-001', 'COIL-TD-08-QUAL-001', 'HT-TD-08-QUAL-001', 'MIDDLE', '2026-06-24 09:24:00', '021001', NULL, '深冲冷轧板', 'DC04-QA0623', '厚度0.80mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_08_2', 'HT-TD-08-EDGE-001', 'COIL-TD-08-EDGE-001', 'HT-TD-08-EDGE-001', 'HEAD', '2026-06-24 10:24:00', '021001', NULL, '深冲冷轧板', 'DC04-QA0623', '厚度0.80mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_08_3', 'HT-TD-08-CONC-001', 'COIL-TD-08-CONC-001', 'HT-TD-08-CONC-001', 'TAIL', '2026-06-24 11:24:00', '021001', NULL, '深冲冷轧板', 'DC04-QA0623', '厚度0.80mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_08_4', 'HT-TD-08-REINS-001', 'COIL-TD-08-REINS-001', 'HT-TD-08-REINS-001', 'MIDDLE', '2026-06-24 12:24:00', '021001', NULL, '深冲冷轧板', 'DC04-QA0623', '厚度0.80mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_08_5', 'HT-TD-08-UNQ-001', 'COIL-TD-08-UNQ-001', 'HT-TD-08-UNQ-001', 'HEAD', '2026-06-24 13:24:00', '021001', NULL, '深冲冷轧板', 'DC04-QA0623', '厚度0.80mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_08_1_1', 'td_ins_08_1', 'ind003', 175, NULL, 'system', NOW(), NOW()),
('td_iv_08_1_2', 'td_ins_08_1', 'ind001', 310, NULL, 'system', NOW(), NOW()),
('td_iv_08_1_3', 'td_ins_08_1', 'ind002', 40, NULL, 'system', NOW(), NOW()),
('td_iv_08_1_4', 'td_ins_08_1', 'ind008', 0.20, NULL, 'system', NOW(), NOW()),
('td_iv_08_2_1', 'td_ins_08_2', 'ind003', 140, NULL, 'system', NOW(), NOW()),
('td_iv_08_2_2', 'td_ins_08_2', 'ind001', 270, NULL, 'system', NOW(), NOW()),
('td_iv_08_2_3', 'td_ins_08_2', 'ind002', 38, NULL, 'system', NOW(), NOW()),
('td_iv_08_2_4', 'td_ins_08_2', 'ind008', 0.18, NULL, 'system', NOW(), NOW()),
('td_iv_08_3_1', 'td_ins_08_3', 'ind003', 135, NULL, 'system', NOW(), NOW()),
('td_iv_08_3_2', 'td_ins_08_3', 'ind001', 310, NULL, 'system', NOW(), NOW()),
('td_iv_08_3_3', 'td_ins_08_3', 'ind002', 40, NULL, 'system', NOW(), NOW()),
('td_iv_08_3_4', 'td_ins_08_3', 'ind008', 0.20, NULL, 'system', NOW(), NOW()),
('td_iv_08_4_1', 'td_ins_08_4', 'ind003', 175, NULL, 'system', NOW(), NOW()),
('td_iv_08_4_2', 'td_ins_08_4', 'ind001', 265, NULL, 'system', NOW(), NOW()),
('td_iv_08_4_3', 'td_ins_08_4', 'ind002', 40, NULL, 'system', NOW(), NOW()),
('td_iv_08_4_4', 'td_ins_08_4', 'ind008', 0.20, NULL, 'system', NOW(), NOW()),
('td_iv_08_5_1', 'td_ins_08_5', 'ind003', 119.99, NULL, 'system', NOW(), NOW()),
('td_iv_08_5_2', 'td_ins_08_5', 'ind001', 310, NULL, 'system', NOW(), NOW()),
('td_iv_08_5_3', 'td_ins_08_5', 'ind002', 40, NULL, 'system', NOW(), NOW()),
('td_iv_08_5_4', 'td_ins_08_5', 'ind008', 0.20, NULL, 'system', NOW(), NOW());
