USE ai_quality_control;

-- ============================================================
-- Inspect sample 011: Q345B_enterprise
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/Q-JH-STEEL-SIM-2026-Q345B_hot_rolled_plate_enterprise.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_11', 'PRODUCT_VARIETY', '热轧板', '热轧板', '', 311, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_11', 'PRODUCT_GRADE', 'Q345B-QA0623', 'Q345B-QA0623', '', 312, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('ind004', '厚度公差', 'Δt', 'DIMENSION', 'mm', '千分尺测厚', '实测厚度与名义厚度之差', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_11_q345b_enterprise', 'ENTERPRISE', 'Q/JH STEEL SIM 010-2026-QA0623', 'Q345B低合金高强度结构钢板企业标准（QA0623隔离模拟企标）', '热轧板', 'Q345B-QA0623', '厚度2.00mm-12.00mm，宽度900mm-1800mm', 'V2026.1-QA0623', '2026-03-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：Q-JH-STEEL-SIM-2026-Q345B_hot_rolled_plate_enterprise.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_11_1', 'td_std_11_q345b_enterprise', 'ind003', NULL, 345, 1, NULL, 335, NOW(), NOW()),
('td_si_11_2', 'td_std_11_q345b_enterprise', 'ind001', 630, 470, 1, NULL, NULL, NOW(), NOW()),
('td_si_11_3', 'td_std_11_q345b_enterprise', 'ind002', NULL, 21, 1, NULL, 20, NOW(), NOW()),
('td_si_11_4', 'td_std_11_q345b_enterprise', 'ind004', 0.2, -0.2, 1, 0.25, -0.25, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_11_1', 'HT-TD-11-QUAL-001', 'COIL-TD-11-QUAL-001', 'HT-TD-11-QUAL-001', 'MIDDLE', '2026-06-25 09:33:00', '021001', NULL, '热轧板', 'Q345B-QA0623', '厚度6.00mm，宽度1500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_11_2', 'HT-TD-11-EDGE-001', 'COIL-TD-11-EDGE-001', 'HT-TD-11-EDGE-001', 'HEAD', '2026-06-25 10:33:00', '021001', NULL, '热轧板', 'Q345B-QA0623', '厚度6.00mm，宽度1500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_11_3', 'HT-TD-11-CONC-001', 'COIL-TD-11-CONC-001', 'HT-TD-11-CONC-001', 'TAIL', '2026-06-25 11:33:00', '021001', NULL, '热轧板', 'Q345B-QA0623', '厚度6.00mm，宽度1500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_11_4', 'HT-TD-11-REINS-001', 'COIL-TD-11-REINS-001', 'HT-TD-11-REINS-001', 'MIDDLE', '2026-06-25 12:33:00', '021001', NULL, '热轧板', 'Q345B-QA0623', '厚度6.00mm，宽度1500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_11_5', 'HT-TD-11-UNQ-001', 'COIL-TD-11-UNQ-001', 'HT-TD-11-UNQ-001', 'HEAD', '2026-06-25 13:33:00', '021001', NULL, '热轧板', 'Q345B-QA0623', '厚度6.00mm，宽度1500mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_11_1_1', 'td_ins_11_1', 'ind003', 370, NULL, 'system', NOW(), NOW()),
('td_iv_11_1_2', 'td_ins_11_1', 'ind001', 550, NULL, 'system', NOW(), NOW()),
('td_iv_11_1_3', 'td_ins_11_1', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_11_1_4', 'td_ins_11_1', 'ind004', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_11_2_1', 'td_ins_11_2', 'ind003', 345, NULL, 'system', NOW(), NOW()),
('td_iv_11_2_2', 'td_ins_11_2', 'ind001', 470, NULL, 'system', NOW(), NOW()),
('td_iv_11_2_3', 'td_ins_11_2', 'ind002', 21, NULL, 'system', NOW(), NOW()),
('td_iv_11_2_4', 'td_ins_11_2', 'ind004', -0.2, NULL, 'system', NOW(), NOW()),
('td_iv_11_3_1', 'td_ins_11_3', 'ind003', 340, NULL, 'system', NOW(), NOW()),
('td_iv_11_3_2', 'td_ins_11_3', 'ind001', 550, NULL, 'system', NOW(), NOW()),
('td_iv_11_3_3', 'td_ins_11_3', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_11_3_4', 'td_ins_11_3', 'ind004', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_11_4_1', 'td_ins_11_4', 'ind003', 370, NULL, 'system', NOW(), NOW()),
('td_iv_11_4_2', 'td_ins_11_4', 'ind001', 465, NULL, 'system', NOW(), NOW()),
('td_iv_11_4_3', 'td_ins_11_4', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_11_4_4', 'td_ins_11_4', 'ind004', 0.0, NULL, 'system', NOW(), NOW()),
('td_iv_11_5_1', 'td_ins_11_5', 'ind003', 324.99, NULL, 'system', NOW(), NOW()),
('td_iv_11_5_2', 'td_ins_11_5', 'ind001', 550, NULL, 'system', NOW(), NOW()),
('td_iv_11_5_3', 'td_ins_11_5', 'ind002', 23, NULL, 'system', NOW(), NOW()),
('td_iv_11_5_4', 'td_ins_11_5', 'ind004', 0.0, NULL, 'system', NOW(), NOW());
