USE ai_quality_control;

-- ============================================================
-- Inspect sample 007: L245M_pipeline
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/GB-T-SIM-9711-2026_L245M_pipeline_steel_national.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_07', 'PRODUCT_VARIETY', '管线钢板卷', '管线钢板卷', '', 271, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_07', 'PRODUCT_GRADE', 'L245M-QA0623', 'L245M-QA0623', '', 272, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_ceq', '碳当量', 'TD_CEQ', 'COMPOSITION', '%', '熔炼分析', '焊接性控制指标', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_07_l245m_pipeline', 'NATIONAL', 'GB/T SIM 9711-2026-QA0623', 'L245M管线钢板卷质量要求（QA0623隔离模拟国标）', '管线钢板卷', 'L245M-QA0623', '厚度4.00mm-16.00mm，宽度1000mm-1800mm', '2026版-QA0623', '2026-04-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：GB-T-SIM-9711-2026_L245M_pipeline_steel_national.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_07_1', 'td_std_07_l245m_pipeline', 'ind003', 450, 245, 1, 460, 235, NOW(), NOW()),
('td_si_07_2', 'td_std_07_l245m_pipeline', 'ind001', 760, 415, 1, NULL, NULL, NOW(), NOW()),
('td_si_07_3', 'td_std_07_l245m_pipeline', 'ind002', NULL, 22, 1, NULL, 20, NOW(), NOW()),
('td_si_07_4', 'td_std_07_l245m_pipeline', 'td_ind_ceq', 0.43, NULL, 1, 0.45, NULL, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_07_1', 'HT-TD-07-QUAL-001', 'COIL-TD-07-QUAL-001', 'HT-TD-07-QUAL-001', 'MIDDLE', '2026-06-24 09:21:00', '021001', NULL, '管线钢板卷', 'L245M-QA0623', '厚度8.00mm，宽度1550mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_07_2', 'HT-TD-07-EDGE-001', 'COIL-TD-07-EDGE-001', 'HT-TD-07-EDGE-001', 'HEAD', '2026-06-24 10:21:00', '021001', NULL, '管线钢板卷', 'L245M-QA0623', '厚度8.00mm，宽度1550mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_07_3', 'HT-TD-07-CONC-001', 'COIL-TD-07-CONC-001', 'HT-TD-07-CONC-001', 'TAIL', '2026-06-24 11:21:00', '021001', NULL, '管线钢板卷', 'L245M-QA0623', '厚度8.00mm，宽度1550mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_07_4', 'HT-TD-07-REINS-001', 'COIL-TD-07-REINS-001', 'HT-TD-07-REINS-001', 'MIDDLE', '2026-06-24 12:21:00', '021001', NULL, '管线钢板卷', 'L245M-QA0623', '厚度8.00mm，宽度1550mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_07_5', 'HT-TD-07-UNQ-001', 'COIL-TD-07-UNQ-001', 'HT-TD-07-UNQ-001', 'HEAD', '2026-06-24 13:21:00', '021001', NULL, '管线钢板卷', 'L245M-QA0623', '厚度8.00mm，宽度1550mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_07_1_1', 'td_ins_07_1', 'ind003', 347.5, NULL, 'system', NOW(), NOW()),
('td_iv_07_1_2', 'td_ins_07_1', 'ind001', 587.5, NULL, 'system', NOW(), NOW()),
('td_iv_07_1_3', 'td_ins_07_1', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_07_1_4', 'td_ins_07_1', 'td_ind_ceq', 0.41, NULL, 'system', NOW(), NOW()),
('td_iv_07_2_1', 'td_ins_07_2', 'ind003', 245, NULL, 'system', NOW(), NOW()),
('td_iv_07_2_2', 'td_ins_07_2', 'ind001', 415, NULL, 'system', NOW(), NOW()),
('td_iv_07_2_3', 'td_ins_07_2', 'ind002', 22, NULL, 'system', NOW(), NOW()),
('td_iv_07_2_4', 'td_ins_07_2', 'td_ind_ceq', 0.43, NULL, 'system', NOW(), NOW()),
('td_iv_07_3_1', 'td_ins_07_3', 'ind003', 240, NULL, 'system', NOW(), NOW()),
('td_iv_07_3_2', 'td_ins_07_3', 'ind001', 587.5, NULL, 'system', NOW(), NOW()),
('td_iv_07_3_3', 'td_ins_07_3', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_07_3_4', 'td_ins_07_3', 'td_ind_ceq', 0.41, NULL, 'system', NOW(), NOW()),
('td_iv_07_4_1', 'td_ins_07_4', 'ind003', 347.5, NULL, 'system', NOW(), NOW()),
('td_iv_07_4_2', 'td_ins_07_4', 'ind001', 410, NULL, 'system', NOW(), NOW()),
('td_iv_07_4_3', 'td_ins_07_4', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_07_4_4', 'td_ins_07_4', 'td_ind_ceq', 0.41, NULL, 'system', NOW(), NOW()),
('td_iv_07_5_1', 'td_ins_07_5', 'ind003', 224.99, NULL, 'system', NOW(), NOW()),
('td_iv_07_5_2', 'td_ins_07_5', 'ind001', 587.5, NULL, 'system', NOW(), NOW()),
('td_iv_07_5_3', 'td_ins_07_5', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_07_5_4', 'td_ins_07_5', 'td_ind_ceq', 0.41, NULL, 'system', NOW(), NOW());
