USE ai_quality_control;

-- ============================================================
-- Inspect sample 015: S355J2_wind_tower
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/Q-JH-STEEL-SIM-050-2026_S355J2_wind_tower_plate_enterprise.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_15', 'PRODUCT_VARIETY', '风电塔筒用中厚板', '风电塔筒用中厚板', '', 351, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_15', 'PRODUCT_GRADE', 'S355J2-QA0623', 'S355J2-QA0623', '', 352, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind001', '抗拉强度', 'Rm', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '最大拉伸力/原始横截面积', 'ACTIVE', 0, NOW(), NOW()),
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_kv2', '冲击功KV2', 'TD_KV2', 'PERFORMANCE', 'J', '夏比V型缺口冲击', '低温冲击吸收能量', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_15_s355j2_wind_tower', 'ENTERPRISE', 'Q/JH STEEL SIM 050-2026-QA0623', 'S355J2风电塔筒用中厚板企业标准（QA0623隔离模拟企标）', '风电塔筒用中厚板', 'S355J2-QA0623', '厚度8.00mm-50.00mm，宽度1800mm-3200mm', 'V2026.1-QA0623', '2026-03-01', '9999-12-31', 'PUBLISHED', NULL, '来源PDF：Q-JH-STEEL-SIM-050-2026_S355J2_wind_tower_plate_enterprise.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_15_1', 'td_std_15_s355j2_wind_tower', 'ind003', NULL, 355, 1, NULL, 345, NOW(), NOW()),
('td_si_15_2', 'td_std_15_s355j2_wind_tower', 'ind001', 630, 470, 1, NULL, NULL, NOW(), NOW()),
('td_si_15_3', 'td_std_15_s355j2_wind_tower', 'ind002', NULL, 22, 1, NULL, 21, NOW(), NOW()),
('td_si_15_4', 'td_std_15_s355j2_wind_tower', 'td_ind_kv2', NULL, 27, 1, NULL, 24, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_15_1', 'HT-TD-15-QUAL-001', 'COIL-TD-15-QUAL-001', 'HT-TD-15-QUAL-001', 'MIDDLE', '2026-06-26 09:45:00', '021001', NULL, '风电塔筒用中厚板', 'S355J2-QA0623', '厚度24.00mm，宽度2500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_15_2', 'HT-TD-15-EDGE-001', 'COIL-TD-15-EDGE-001', 'HT-TD-15-EDGE-001', 'HEAD', '2026-06-26 10:45:00', '021001', NULL, '风电塔筒用中厚板', 'S355J2-QA0623', '厚度24.00mm，宽度2500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_15_3', 'HT-TD-15-CONC-001', 'COIL-TD-15-CONC-001', 'HT-TD-15-CONC-001', 'TAIL', '2026-06-26 11:45:00', '021001', NULL, '风电塔筒用中厚板', 'S355J2-QA0623', '厚度24.00mm，宽度2500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_15_4', 'HT-TD-15-REINS-001', 'COIL-TD-15-REINS-001', 'HT-TD-15-REINS-001', 'MIDDLE', '2026-06-26 12:45:00', '021001', NULL, '风电塔筒用中厚板', 'S355J2-QA0623', '厚度24.00mm，宽度2500mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_15_5', 'HT-TD-15-UNQ-001', 'COIL-TD-15-UNQ-001', 'HT-TD-15-UNQ-001', 'HEAD', '2026-06-26 13:45:00', '021001', NULL, '风电塔筒用中厚板', 'S355J2-QA0623', '厚度24.00mm，宽度2500mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_15_1_1', 'td_ins_15_1', 'ind003', 380, NULL, 'system', NOW(), NOW()),
('td_iv_15_1_2', 'td_ins_15_1', 'ind001', 550, NULL, 'system', NOW(), NOW()),
('td_iv_15_1_3', 'td_ins_15_1', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_15_1_4', 'td_ins_15_1', 'td_ind_kv2', 29, NULL, 'system', NOW(), NOW()),
('td_iv_15_2_1', 'td_ins_15_2', 'ind003', 355, NULL, 'system', NOW(), NOW()),
('td_iv_15_2_2', 'td_ins_15_2', 'ind001', 470, NULL, 'system', NOW(), NOW()),
('td_iv_15_2_3', 'td_ins_15_2', 'ind002', 22, NULL, 'system', NOW(), NOW()),
('td_iv_15_2_4', 'td_ins_15_2', 'td_ind_kv2', 27, NULL, 'system', NOW(), NOW()),
('td_iv_15_3_1', 'td_ins_15_3', 'ind003', 350, NULL, 'system', NOW(), NOW()),
('td_iv_15_3_2', 'td_ins_15_3', 'ind001', 550, NULL, 'system', NOW(), NOW()),
('td_iv_15_3_3', 'td_ins_15_3', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_15_3_4', 'td_ins_15_3', 'td_ind_kv2', 29, NULL, 'system', NOW(), NOW()),
('td_iv_15_4_1', 'td_ins_15_4', 'ind003', 380, NULL, 'system', NOW(), NOW()),
('td_iv_15_4_2', 'td_ins_15_4', 'ind001', 465, NULL, 'system', NOW(), NOW()),
('td_iv_15_4_3', 'td_ins_15_4', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_15_4_4', 'td_ins_15_4', 'td_ind_kv2', 29, NULL, 'system', NOW(), NOW()),
('td_iv_15_5_1', 'td_ins_15_5', 'ind003', 334.99, NULL, 'system', NOW(), NOW()),
('td_iv_15_5_2', 'td_ins_15_5', 'ind001', 550, NULL, 'system', NOW(), NOW()),
('td_iv_15_5_3', 'td_ins_15_5', 'ind002', 24, NULL, 'system', NOW(), NOW()),
('td_iv_15_5_4', 'td_ins_15_5', 'td_ind_kv2', 29, NULL, 'system', NOW(), NOW());
