USE ai_quality_control;

-- ============================================================
-- Inspect sample 018: DX56D_Z_customer_BYEV
-- Source PDF: /Users/weixuelei/workspace/aiAgent/ai-project/for-test/std-doc/CUST-BYEV-SIM-2026-DX56D-Z_customer_agreement.pdf
-- Rerunnable: INSERT IGNORE only.
-- Direct SQL insertion does not invoke InspectionService.addRecord().
-- Use the API payloads in the paired MD file when automatic judgment must be generated by service logic.
-- ============================================================

INSERT IGNORE INTO sys_dict_item
(id, dict_code, item_value, item_label, color_tag, sort_no, status, is_system, remark, create_date_time, update_date_time)
VALUES
('td_var_18', 'PRODUCT_VARIETY', '热镀锌深冲板', '热镀锌深冲板', '', 381, 1, 0, '测试包：100份检验记录样例', NOW(), NOW()),
('td_grade_18', 'PRODUCT_GRADE', 'DX56D+Z-QA0623', 'DX56D+Z-QA0623', '', 382, 1, 0, '测试包：结构化牌号使用QA0623后缀，避免历史脏数据', NOW(), NOW()),
('td_cust_18', 'QC_CUSTOMER', 'TD-CUST-BYEV', '北源新能源', '', 383, 1, 0, '测试包：客户协议检验记录样例', NOW(), NOW());

INSERT IGNORE INTO qc_indicator_item
(id, indicator_name, indicator_code, indicator_category, unit, test_method, description, status, is_deleted, create_date_time, update_date_time)
VALUES
('ind002', '延伸率', 'A', 'PERFORMANCE', '%', 'GB/T 228.1', '断后伸长量/原始标距长度', 'ACTIVE', 0, NOW(), NOW()),
('ind003', '屈服强度', 'ReL', 'PERFORMANCE', 'MPa', 'GB/T 228.1', '屈服点的应力值', 'ACTIVE', 0, NOW(), NOW()),
('ind004', '厚度公差', 'Δt', 'DIMENSION', 'mm', '千分尺测厚', '实测厚度与名义厚度之差', 'ACTIVE', 0, NOW(), NOW()),
('td_ind_coat_mass', '镀层重量', 'TD_COAT', 'PERFORMANCE', 'g/m2', '三点称量法', '双面镀层重量', 'ACTIVE', 0, NOW(), NOW());

INSERT IGNORE INTO qc_quality_standard
(id, standard_type, standard_code, standard_name, variety, grade, spec_range, version_no, effective_date, expiry_date, status, customer_id, remark, create_user_no, create_date_time, update_date_time)
VALUES
('td_std_18_dx56d_z_customer_byev', 'CUSTOMER', 'AGREEMENT BYEV-SIM-2026-003-QA0623', '北源新能源DX56D+Z热镀锌深冲板供货质量协议（QA0623隔离模拟客户协议）', '热镀锌深冲板', 'DX56D+Z-QA0623', '厚度0.60mm-1.60mm，宽度900mm-1450mm', '协议V1.0-QA0623', '2026-03-01', '2026-12-31', 'PUBLISHED', 'TD-CUST-BYEV', '来源PDF：CUST-BYEV-SIM-2026-DX56D-Z_customer_agreement.pdf；结构化牌号使用QA0623后缀以避让历史脏数据', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_standard_indicator
(id, standard_id, indicator_id, upper_limit, lower_limit, is_required, concession_upper, concession_lower, create_date_time, update_date_time)
VALUES
('td_si_18_1', 'td_std_18_dx56d_z_customer_byev', 'ind002', NULL, 39, 1, NULL, 37, NOW(), NOW()),
('td_si_18_2', 'td_std_18_dx56d_z_customer_byev', 'td_ind_coat_mass', 140, 70, 1, NULL, NULL, NOW(), NOW()),
('td_si_18_3', 'td_std_18_dx56d_z_customer_byev', 'ind003', 180, 120, 1, 190, 110, NOW(), NOW()),
('td_si_18_4', 'td_std_18_dx56d_z_customer_byev', 'ind004', 0.05, -0.05, 1, 0.06, -0.06, NOW(), NOW());

INSERT IGNORE INTO qc_inspection_record
(id, heat_no, coil_no, batch_no, sample_type, test_time, tester_no, customer_id, product_variety, product_grade, product_spec, status, create_user_no, create_date_time, update_date_time)
VALUES
('td_ins_18_1', 'HT-TD-18-QUAL-001', 'COIL-TD-18-QUAL-001', 'HT-TD-18-QUAL-001', 'MIDDLE', '2026-06-27 09:54:00', '021001', 'TD-CUST-BYEV', '热镀锌深冲板', 'DX56D+Z-QA0623', '厚度0.80mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_18_2', 'HT-TD-18-EDGE-001', 'COIL-TD-18-EDGE-001', 'HT-TD-18-EDGE-001', 'HEAD', '2026-06-27 10:54:00', '021001', 'TD-CUST-BYEV', '热镀锌深冲板', 'DX56D+Z-QA0623', '厚度0.80mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_18_3', 'HT-TD-18-CONC-001', 'COIL-TD-18-CONC-001', 'HT-TD-18-CONC-001', 'TAIL', '2026-06-27 11:54:00', '021001', 'TD-CUST-BYEV', '热镀锌深冲板', 'DX56D+Z-QA0623', '厚度0.80mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_18_4', 'HT-TD-18-REINS-001', 'COIL-TD-18-REINS-001', 'HT-TD-18-REINS-001', 'MIDDLE', '2026-06-27 12:54:00', '021001', 'TD-CUST-BYEV', '热镀锌深冲板', 'DX56D+Z-QA0623', '厚度0.80mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW()),
('td_ins_18_5', 'HT-TD-18-UNQ-001', 'COIL-TD-18-UNQ-001', 'HT-TD-18-UNQ-001', 'HEAD', '2026-06-27 13:54:00', '021001', 'TD-CUST-BYEV', '热镀锌深冲板', 'DX56D+Z-QA0623', '厚度0.80mm，宽度1250mm', 'NORMAL', 'system', NOW(), NOW());

INSERT IGNORE INTO qc_inspection_value
(id, record_id, indicator_id, test_value, value_text, create_user_no, create_date_time, update_date_time)
VALUES
('td_iv_18_1_1', 'td_ins_18_1', 'ind002', 41, NULL, 'system', NOW(), NOW()),
('td_iv_18_1_2', 'td_ins_18_1', 'td_ind_coat_mass', 105, NULL, 'system', NOW(), NOW()),
('td_iv_18_1_3', 'td_ins_18_1', 'ind003', 150, NULL, 'system', NOW(), NOW()),
('td_iv_18_1_4', 'td_ins_18_1', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_18_2_1', 'td_ins_18_2', 'ind002', 39, NULL, 'system', NOW(), NOW()),
('td_iv_18_2_2', 'td_ins_18_2', 'td_ind_coat_mass', 70, NULL, 'system', NOW(), NOW()),
('td_iv_18_2_3', 'td_ins_18_2', 'ind003', 120, NULL, 'system', NOW(), NOW()),
('td_iv_18_2_4', 'td_ins_18_2', 'ind004', -0.05, NULL, 'system', NOW(), NOW()),
('td_iv_18_3_1', 'td_ins_18_3', 'ind002', 38, NULL, 'system', NOW(), NOW()),
('td_iv_18_3_2', 'td_ins_18_3', 'td_ind_coat_mass', 105, NULL, 'system', NOW(), NOW()),
('td_iv_18_3_3', 'td_ins_18_3', 'ind003', 150, NULL, 'system', NOW(), NOW()),
('td_iv_18_3_4', 'td_ins_18_3', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_18_4_1', 'td_ins_18_4', 'ind002', 41, NULL, 'system', NOW(), NOW()),
('td_iv_18_4_2', 'td_ins_18_4', 'td_ind_coat_mass', 69.5, NULL, 'system', NOW(), NOW()),
('td_iv_18_4_3', 'td_ins_18_4', 'ind003', 150, NULL, 'system', NOW(), NOW()),
('td_iv_18_4_4', 'td_ins_18_4', 'ind004', 0.00, NULL, 'system', NOW(), NOW()),
('td_iv_18_5_1', 'td_ins_18_5', 'ind002', 34.99, NULL, 'system', NOW(), NOW()),
('td_iv_18_5_2', 'td_ins_18_5', 'td_ind_coat_mass', 105, NULL, 'system', NOW(), NOW()),
('td_iv_18_5_3', 'td_ins_18_5', 'ind003', 150, NULL, 'system', NOW(), NOW()),
('td_iv_18_5_4', 'td_ins_18_5', 'ind004', 0.00, NULL, 'system', NOW(), NOW());
